### ISSUE TITLE
-np 禁ping时的BUG

### ISSUE THREAD

**Issue by butnomingzi** [shadow1ng/fscan#10]
环境MAC(windows下正常)
# 辛苦作者大大

正常情况下：
```
go run main.go -h 172.20.10.1/24

(Ping) Target '172.20.10.15' is alive
(Ping) Target '172.20.10.1' is alive
(Ping) Target '172.20.10.3' is alive
icmp alive hosts len is: 3
172.20.10.1:21 open
```

在`-np`下扫描导致错误，并且无法自动结束。
```
go run main.go -h 172.20.10.1/24 -np

172.20.10.63:21 open
172.20.10.29:21 open
172.20.10.62:21 open
open result.txt: too many open files
open result.txt: too many open files
172.20.10.64:21 open
open result.txt: too many open files
172.20.10.54:21 open
open result.txt: too many open files
...
```

**Comment by shadow1ng** [comment]
可以尝试使用新版本，新版本中加入了os.O_WRONLY参数，防止报错。 
 os.OpenFile(filename, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0777)

**Comment by butnomingzi** [comment]
刚刚下载了最新版本，MAC还有部分问题，不过问题不大，谢谢作者大大。
```
 ./fscan_darwin -h 192.168.1.1/24 -np
scan start
192.168.1.13:80 open
**_open result.txt: too many open files_**
192.168.1.13:22 open
192.168.1.68:80 open
```

**Comment by uyid** [comment]
func WriteFile(result string, filename string) {
	var text = []byte(result + "\n")
	fl, err := os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0777)
	if err != nil {
		fmt.Println("Open %s error, %v", filename, err)
		return
	}
	_, err = fl.Write(text)
	fl.Close()
	if err != nil {
		fmt.Println("write %s error, %v", filename, err)
	}
}

fl遍历改成全局变量,不要每次写入都打开好一些

**Comment by shadow1ng** [comment]
> func WriteFile(result string, filename string) {
> var text = []byte(result + "\n")
> fl, err := os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0777)
> if err != nil {
> fmt.Println("Open %s error, %v", filename, err)
> return
> }
> _, err = fl.Write(text)
> fl.Close()
> if err != nil {
> fmt.Println("write %s error, %v", filename, err)
> }
> }
> 
> fl变量改成全局变量,不要每次写入都打开好一些

设置成全局变量的话，会一直占用文件，有时候移动、修改不太方便

**Comment by uyid** [comment]
复制就好了

**Comment by shadow1ng** [comment]
https://blog.csdn.net/zmh458/article/details/105096964/
ulimit -n 4096(非root用户限制到4096)
