### ISSUE TITLE
Unsolicited response问题

### ISSUE THREAD

**Issue by FFFrankkkkk** [shadow1ng/fscan#100]
![image](https://user-images.githubusercontent.com/38023553/135227522-ea67bd3d-206b-43b5-aee3-8c891d2e53ce.png)
大佬好，扫描的时候出现这个就一直卡着不往下运行了是什么原因呢？

**Comment by shadow1ng** [comment]
这个不影响扫描，这个是http包，超时后又出现相应包造成的
