### ISSUE TITLE
表哥好 提示 undefined: MS17010EXP 与 not enough arguments in call to 错误

### ISSUE THREAD

**Issue by sevendian** [shadow1ng/fscan#104]
PS D:\0000\20211012\kill-free\fscan\2021-10-12\fscan-main\fscan-main> go env -w GOPROXY=https://goproxy.cn,direct
PS D:\0000\20211012\kill-free\fscan\2021-10-12\fscan-main\fscan-main> go mod tidy
PS D:\0000\20211012\kill-free\fscan\2021-10-12\fscan-main\fscan-main> go build -ldflags="-s -w " -trimpath
# github.com/shadow1ng/fscan/Plugins
Plugins\ms17010.go:133:4: undefined: MS17010EXP
Plugins\scanner.go:16:28: not enough arguments in call to "github.com/shadow1ng/fscan/common".ParseIP
        have (string, string)
        want (string, string, string)

**Comment by nu1l1** [comment]
17010 难道只有我还是报错了？

`# github.com/shadow1ng/fscan/Plugins
Plugins/ms17010.go:133:4: undefined: MS17010EXP`
