### ISSUE TITLE
能否 -pf 使用端口列表文件

### ISSUE THREAD

**Issue by tysmlq** [shadow1ng/fscan#105]
感谢作者提供的fscan工具，很好用，还会继续测试。
问题1：有时需要探测的端口较多，命令行逐个输入不方便，能否-pf读取port文件？
问题2：kali下该用哪个fscan文件？能否给个下载链接

**Comment by tysmlq** [comment]
感谢回复。
kali（Linux kali 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux）下运行fscan_amd64提示“总线错误“。

**Comment by shadow1ng** [comment]
可能是github访问失败吧。
可以先下载到本机，然后复制到kali。
-pf我更新了代码，但没更新release，所以要使用的话，最好 git clone,然后go run main.go
