### ISSUE TITLE
你这个powershell好酷，，有教程吗

### ISSUE THREAD

**Issue by 3hxks** [shadow1ng/fscan#114]
powershell好酷，，有教程吗

**Comment by shadow1ng** [comment]
用windows 官方的terminal ，然后自定义背景图就行

**Comment by shadow1ng** [comment]
![powershell](https://user-images.githubusercontent.com/39651966/99139727-41fc9200-2676-11eb-8957-c851c12b5a2c.jpg)

**Comment by 3hxks** [comment]
谢谢
