### ISSUE TITLE
入门3天的golang小白，有一行代码不理解，求教

### ISSUE THREAD

**Issue by 0x25w** [shadow1ng/fscan#116]
如图，此处的ip[len(ip)-3:]是什么意思，

![image](https://user-images.githubusercontent.com/72005182/144185414-42bef713-da97-4077-857b-26d8fd493636.png)

此处ip为string类型，假设输入的参数是192.168.1.0/24  
那么减去3个字节就是192.168.1.0了 就和之前的参数压根不一样了，勿笑啊大佬们

**Comment by shadow1ng** [comment]
如果结尾位是/24，那就走c段解析函数

**Comment by shadow1ng** [comment]
c段解析函数里,会根据"."隔开，strings.Split(realIP, ".")[0:3],获取到前三位,192.168.1,这时候再在末尾加上 "."+ (0-255)

**Comment by 0x25w** [comment]
多谢，我再捋一捋，

另外，你这个代码写的很整齐，小白入门感觉非常不错,
赞

**Comment by 0x25w** [comment]
懂了，是在下跳过太多基础了，原来s[len(s)-3:]是取后三位，被自己气活了，蟹蟹
