### ISSUE TITLE
批量扫描，然后出问题了

### ISSUE THREAD

**Issue by decadecaomm** [shadow1ng/fscan#117]
显示host parsing error，是每个ip要用 , 隔开吗？

**Comment by decadecaomm** [comment]
已经用 , 隔开了，但是还是显示host parsing error....，而且每个地址也换行了

**Comment by shadow1ng** [comment]
可以看看输入的ip 嘛？

**Comment by shadow1ng** [comment]
不行的话，先用前一个版本的源码吧，我检查检查原因

**Comment by decadecaomm** [comment]
似乎是切片错误什么的...是限制了扫描的ip数量吗？

**Comment by shadow1ng** [comment]
我晚上检查一下，今天一直在外出

**Comment by decadecaomm** [comment]
好的

**Comment by decadecaomm** [comment]
不知道老哥的弱口令库是多大？

**Comment by shadow1ng** [comment]
https://github.com/shadow1ng/fscan/blob/main/common/config.go

**Comment by shadow1ng** [comment]
找到原因了,把下面这个删掉就行了
parseip.go
```
	if host == "" {
		return
	}
```

**Comment by decadecaomm** [comment]
好的
