### ISSUE TITLE
关于批量扫描优化的问题 -hf参数介绍写错了

### ISSUE THREAD

**Issue by Chinakentgao** [shadow1ng/fscan#118]
ip.txt的格式必须得ip1,ip2这样编辑起来太麻烦了。调整下源码支持一行一个ip的格式吧。不然还得花时间去处理格式。ip少还好多了就很难弄了。还有你readme.md里面-hf 里面是-hf ip.txt 你写成-hs ip.txt

**Comment by shadow1ng** [comment]
支持换行

**Comment by Chinakentgao** [comment]
> 支持换行
parseip.go

	if host == "" {
		return
	}
这个删了才支持，刚没删之前是不支持的

**Comment by shadow1ng** [comment]
readme改好了。是，昨天忘记-hf时会导致-h 为空的返回了

**Comment by Chinakentgao** [comment]
> readme改好了。是，昨天忘记-hf时会导致-h 为空的返回了

-nobr你得加入到readme.md源码里面的提示也是。经常忘记每次都跑来最近更新看下才知道。

**Comment by shadow1ng** [comment]
是的了，多谢提醒

**Comment by shadow1ng** [comment]
改好readme了，还有哪些需要改进的嘛?

**Comment by Chinakentgao** [comment]
> 
能不能来个全端口扫描的选项，这样的话NMAP我都省了 哈哈

**Comment by Chinakentgao** [comment]
> 改好readme了，还有哪些需要改进的嘛?

能不能来个全端口扫描的选项，这样的话NMAP我都省了 哈哈

**Comment by shadow1ng** [comment]
这个-p 1-65535就行了
