### ISSUE TITLE
m1 版本什么时候更新呀师傅

### ISSUE THREAD

**Issue by Steady-brother** [shadow1ng/fscan#119]

**Comment by shadow1ng** [comment]
师傅可以 go build -ldflags="-s -w " -trimpath 编译一下

**Comment by Dawnnnnnn** [comment]
我Fork的版本里有自动打包的M1版本，可以临时用着，等作者打新tag的时候这个仓库就会自动打包各种版本了

**Comment by shadow1ng** [comment]
@Dawnnnnnn 师傅，话说那个github actions 可以加个upx -9 嘛?

**Comment by Dawnnnnnn** [comment]
> @Dawnnnnnn 师傅，话说那个github actions 可以加个upx -9 嘛?

等我周末研究一下，马上要下班了hhhhh

**Comment by shadow1ng** [comment]
> > @Dawnnnnnn 师傅，话说那个github actions 可以加个upx -9 嘛?
> 
> 等我周末研究一下，马上要下班了hhhhh

可以可以

**Comment by Is4b3lla3** [comment]
> 我Fork的版本里有自动打包的M1版本，可以临时用着，等作者打新tag的时候这个仓库就会自动打包各种版本了

师傅我运行m1版本的显示这个，似乎不能用
![image](https://user-images.githubusercontent.com/37106292/149276553-c5b71294-2098-449f-9133-4c62e48c1dba.png)

**Comment by Dawnnnnnn** [comment]
> > 我Fork的版本里有自动打包的M1版本，可以临时用着，等作者打新tag的时候这个仓库就会自动打包各种版本了
> 
> 师傅我运行m1版本的显示这个，似乎不能用 ![image](https://user-images.githubusercontent.com/37106292/149276553-c5b71294-2098-449f-9133-4c62e48c1dba.png)

确实，等我有空看一下是不是upx的原因
