### ISSUE TITLE
vulscan过程中会卡死

### ISSUE THREAD

**Issue by Linyoung666** [shadow1ng/fscan#125]
师傅，怎么每次到vulscan阶段的时候就会卡死啊。而且也没有打印进度，我的命令是这样的`.\fscan64.exe -h c段 -debug 10`

**Comment by shadow1ng** [comment]
我这边好像测试没什么问题。师傅可以下载最新代码自己编译试试
![image](https://user-images.githubusercontent.com/39651966/146502569-be99ce7c-dc58-45e9-862e-3c79b721fd65.png)

**Comment by shadow1ng** [comment]
尝试进行修复了，对webscan模块加了超时
