### ISSUE TITLE
20211207的版本/8不再扫描网关

### ISSUE THREAD

**Issue by um3ha4a** [shadow1ng/fscan#128]
rt
-h 10.0.0.0/8不再扫描网关，而是分配大量内存全扫

**Comment by shadow1ng** [comment]
噢，我找时间修改下

**Comment by shadow1ng** [comment]
已更新
![image](https://user-images.githubusercontent.com/39651966/148497594-70cb18c1-dec4-43b2-9179-b4052ab6c270.png)
