### ISSUE TITLE
Ability to scan a URLs list

### ISSUE THREAD

**Issue by Teicu** [shadow1ng/fscan#129]
Hi 

First of all, thanks for this tool. It's great! I like it very much and works like a charm 

I wonder if it is possible to scan a list in text format of URL addresses, or just IPs?  

If so, then can you show me some examples?

Cheers

**Comment by shadow1ng** [comment]
-u baidu.com
-uf url.txt

**Comment by Teicu** [comment]
Thank you very much. 

Regards
