### ISSUE TITLE
shiro存在误报

### ISSUE THREAD

**Issue by cwkiller** [shadow1ng/fscan#13]
可能是解析yaml出问题了
![image](https://user-images.githubusercontent.com/19302055/102166656-8e323080-3ec7-11eb-9395-fe9fec47ce99.png)
![image](https://user-images.githubusercontent.com/19302055/102166669-97bb9880-3ec7-11eb-8162-da9c8eee0140.png)

**Comment by shadow1ng** [comment]
这个我昨天下午重新改了改,yaml，你试试重新下载呢
