### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by P4r4d1se** [shadow1ng/fscan#134]
D:\Code\Golang\fscan>go build -ldflags="-s -w " -trimpath
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%

下载昨天更新go.mod之后的版本出现了这个问题，3天前那版可以正常编译。

**Comment by shadow1ng** [comment]
关闭gcc。go env -w CGO_ENABLED=0

**Comment by P4r4d1se** [comment]
**又出现新的错误：**
D:\Code\Golang\fscan>go build -ldflags="-s -w " -trimpath
package github.com/shadow1ng/fscan
        imports github.com/shadow1ng/fscan/Plugins
        imports github.com/tomatome/grdp/protocol/pdu
        imports github.com/tomatome/grdp/protocol/t125/gcc
        imports github.com/tomatome/grdp/plugin: build constraints exclude all Go files in C:\Users\xxx\go\pkg\mod\github.com\shadow1ng\grdp@v1.0.4\plugin

**Comment by shadow1ng** [comment]
go mod tidy
go build -ldflags="-s -w " -trimpath
我这边测试，重新下载源码、编译、运行都是可以的
![image](https://user-images.githubusercontent.com/39651966/149473197-106a4ddf-cae3-4681-b415-460877462d59.png)

**Comment by P4r4d1se** [comment]
可能环境配置有什么差异吧，好像是1.0.4版的grdp多出来的plugin目录导致的，我先用1.0.3的吧。

**Comment by um3ha4a** [comment]
go build -ldflags="-s -w " -trimpath 这样编linux是可以的
GOOS=windows GOARCH=amd64 go build -ldflags="-s -w " -trimpath 这样编windows报错

**Comment by shadow1ng** [comment]
> go build -ldflags="-s -w " -trimpath 这样编linux是可以的 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w " -trimpath 这样编windows报错

那师傅先用这个版本吧 https://github.com/shadow1ng/fscan/commit/3b23c93c3571b05a26b827b9f22d89bdc514667a

**Comment by shadow1ng** [comment]
我先把grdp的版本修改为前一个版本了，避免编译报错
