### ISSUE TITLE
昨天的这个版本grdp编译报错，跟go.sum相关

### ISSUE THREAD

**Issue by um3ha4a** [shadow1ng/fscan#135]
`GOOS=windows GOARCH=amd64 go build -ldflags="-s -w " -trimpath`
go: github.com/sijms/go-ora/v2@v2.2.16: missing go.sum entry; to add it:
        go mod download github.com/sijms/go-ora/v2
go: github.com/sijms/go-ora/v2@v2.2.16: missing go.sum entry; to add it:

`root@iPhone:~/go/fscan# go mod download github.com/sijms/go-ora/v2`
`root@iPhone:~/go/fscan# GOOS=windows GOARCH=amd64 go build -ldflags="-s -w " -trimpath`
Plugins/rdp.go:7:2: missing go.sum entry for module providing package github.com/tomatome/grdp/core (imported by github.com/shadow1ng/fscan/Plugins); to add:
        go get github.com/shadow1ng/fscan/Plugins
Plugins/rdp.go:8:2: missing go.sum entry for module providing package github.com/tomatome/grdp/glog (imported by github.com/shadow1ng/fscan/Plugins); to add:
        go get github.com/shadow1ng/fscan/Plugins
Plugins/rdp.go:9:2: missing go.sum entry for module providing package github.com/tomatome/grdp/protocol/nla (imported by github.com/shadow1ng/fscan/Plugins); to add:
        go get github.com/shadow1ng/fscan/Plugins
Plugins/rdp.go:10:2: missing go.sum entry for module providing package github.com/tomatome/grdp/protocol/pdu (imported by github.com/shadow1ng/fscan/Plugins); to add:
        go get github.com/shadow1ng/fscan/Plugins
Plugins/rdp.go:11:2: missing go.sum entry for module providing package github.com/tomatome/grdp/protocol/rfb (imported by github.com/shadow1ng/fscan/Plugins); to add:
        go get github.com/shadow1ng/fscan/Plugins
Plugins/rdp.go:12:2: missing go.sum entry for module providing package github.com/tomatome/grdp/protocol/sec (imported by github.com/shadow1ng/fscan/Plugins); to add:
        go get github.com/shadow1ng/fscan/Plugins
Plugins/rdp.go:13:2: missing go.sum entry for module providing package github.com/tomatome/grdp/protocol/t125 (imported by github.com/shadow1ng/fscan/Plugins); to add:
        go get github.com/shadow1ng/fscan/Plugins
Plugins/rdp.go:14:2: missing go.sum entry for module providing package github.com/tomatome/grdp/protocol/tpkt (imported by github.com/shadow1ng/fscan/Plugins); to add:
        go get github.com/shadow1ng/fscan/Plugins
Plugins/rdp.go:15:2: missing go.sum entry for module providing package github.com/tomatome/grdp/protocol/x224 (imported by github.com/shadow1ng/fscan/Plugins); to add:
        go get github.com/shadow1ng/fscan/Plugins

`root@iPhone:~/go/fscan# go get github.com/shadow1ng/fscan/Plugins`
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
`root@iPhone:~/go/fscan# GOOS=windows GOARCH=amd64 go build -ldflags="-s -w " -trimpath`
package github.com/shadow1ng/fscan
        imports github.com/shadow1ng/fscan/Plugins
        imports github.com/tomatome/grdp/protocol/pdu
        imports github.com/tomatome/grdp/protocol/t125/gcc
        imports github.com/tomatome/grdp/plugin: build constraints exclude all Go files in /root/go/pkg/mod/github.com/shadow1ng/grdp@v1.0.4/plugin

**Comment by shadow1ng** [comment]
go mod tidy

**Comment by shadow1ng** [comment]
https://github.com/shadow1ng/fscan/issues/134

**Comment by um3ha4a** [comment]
`root@iPhone:~/go/fscan# go mod tidy`
go: downloading github.com/stretchr/testify v1.6.1
go: downloading gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
`root@iPhone:~/go/fscan# GOOS=windows GOARCH=amd64 go build -ldflags="-s -w " -trimpath`
package github.com/shadow1ng/fscan
        imports github.com/shadow1ng/fscan/Plugins
        imports github.com/tomatome/grdp/protocol/pdu
        imports github.com/tomatome/grdp/protocol/t125/gcc
        imports github.com/tomatome/grdp/plugin: build constraints exclude all Go files in /root/go/pkg/mod/github.com/shadow1ng/grdp@v1.0.4/plugin

**Comment by WasteMaterial** [comment]
看了半天师傅们精彩的演讲,俺试了好久终于是编译成功了

**Comment by msjie1** [comment]
> 
怎么编译的啊?

**Comment by shadow1ng** [comment]
> > 
> 
> 怎么编译的啊?

go mod tidy
go build main.go
