### ISSUE TITLE
关于存活探测问题

### ISSUE THREAD

**Issue by xiaosage666** [shadow1ng/fscan#136]
我想问下师傅 这个一键扫描 windows 防火墙默认开启拦截icmp包 也就是默认ping不通 ，然后这个一键扫描用的就是ping,然后自然的没有发现这个机器的存活，然后就没有下一步端口扫描服务探测了，那么问题来了，这个工具需要前期自己用msf arp等内网存活工具探测一遍吗

**Comment by shadow1ng** [comment]
禁ping情况下，可以用-np参数，跳过存活探测。  arp只能探测c段，不能探测b段。
可以先-h xxx -np -p 22,80,443,445... -nobr 简单扫下网段端口
