### ISSUE TITLE
mssql爆破问题

### ISSUE THREAD

**Issue by yqcs** [shadow1ng/fscan#137]
如题，如果我的服务器在1433端口开放个Http服务，那么当fscan扫描该服务执行mssql爆破的时候会直接卡死。

**Comment by shadow1ng** [comment]
因为没加指纹识别的原因，会有无效爆破。但加指纹识别，也会加大发包量，所以还在考虑下一步优化

**Comment by yqcs** [comment]
我认为可以给每个爆破单开个线程，超时直接丢弃该线程
