### ISSUE TITLE
编译好的1.7.0版本无oracle爆破模块

### ISSUE THREAD

**Issue by xxsmile123** [shadow1ng/fscan#138]
go版本：
go version go1.17.6 windows/amd64
操作系统版本：
win10 1909 企业版 X64
模块查看：
![image](https://user-images.githubusercontent.com/43473886/153107549-1de90986-0012-427a-92d7-365e22751140.png)

**Comment by shadow1ng** [comment]
更新上去了

**Comment by xxsmile123** [comment]
感谢大佬更新
