### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by teamtopkarl** [shadow1ng/fscan#139]
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 60870 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x4, 0x1a75e60)
        reflect/value.go:1908 +0x190
github.com/shadow1ng/fscan/Plugins.ScanFunc(0xc000375380, 0xc0004aa30e, 0x4, 0xc0008adf98, 0x1, 0x1, 0xc0008adf98, 0x5300, 0x453b3d, 0x1021108, ...)
        github.com/shadow1ng/fscan/Plugins/scanner.go:106 +0x105
github.com/shadow1ng/fscan/Plugins.AddScan.func1(0xc0004aa30e, 0x4, 0xc0004f5300, 0xc0003c0420, 0xc000072960)
        github.com/shadow1ng/fscan/Plugins/scanner.go:94 +0xcd
created by github.com/shadow1ng/fscan/Plugins.AddScan
        github.com/shadow1ng/fscan/Plugins/scanner.go:90 +0xdd

**Comment by teamtopkarl** [comment]
扫描报错，是偶然情况

**Comment by shadow1ng** [comment]
已更新
