### ISSUE TITLE
Unsolicited response received on idle HTTP channel starting with报错后终止。

### ISSUE THREAD

**Issue by Laura0xiaoshizi** [shadow1ng/fscan#14]
2020/12/19 22:34:53 Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 200 OK\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nContent-Type: text/html\r\nX-Download-Options: noopen\r\nX-Frame-Options: SAMEORIGIN\r\nX-XSS-Protection: 1; mode=block\r\nContent-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval'\r\nX-Content-Type-Options: nosniff\r\nDate: Sat, 19 Dec 2020 14:34:47 GMT\r\nConnection: Keep-Alive\r\nContent-Language: en\r\nContent-Length: 5551\r\n\r\n"; err=<nil>

报错后终止。

![图片](https://user-images.githubusercontent.com/31725824/102692659-c0d58380-424f-11eb-8e00-51293a22a4e8.png)

还有想问一下linux最后跑弱口令，都结束了会卡很久是啥原因？

**Comment by shadow1ng** [comment]
收到反馈。第一个问题  我先看看是不是http超时处理问题。第二个问题可能是卡在某个服务爆破了。我再检查检查代码

**Comment by Laura0xiaoshizi** [comment]
> 
> 
> 收到反馈。第一个问题 我先看看是不是http超时处理问题。第二个问题可能是卡在某个服务爆破了。我再检查检查代码

第二个问题不是偶尔的，是一直都有这个问题。新版本我还没试，以前1.3应该是有这个问题的。

**Comment by shadow1ng** [comment]
第二个问题，1.4版本我改了挺多超时处理，应该好很多了，师傅可以试试的。第一个问题的话，是报错提醒，应该不会终止，原因应该是超时之后，服务器又有响应了导致的报错，加了DisableKeepAlives: false 参数，应该会好一些.

**Comment by sinlee1** [comment]
- 环境：Win08R2 32位系统下报错 ，执行到一半后就出现这个错误

![image](https://user-images.githubusercontent.com/29684167/102863718-f1930400-446d-11eb-8055-8f9c463e8b1b.png)

**Comment by shadow1ng** [comment]
新版本 -debug参数可以查看卡在哪个模块了。http报错是超时之后再响应，导致的内部库报错，不影响使用
