### ISSUE TITLE
mysql模块问题

### ISSUE THREAD

**Issue by teamtopkarl** [shadow1ng/fscan#141]
[mysql] 2022/02/18 11:01:45 packets.go:37: unexpected EOF

**Comment by shadow1ng** [comment]
可以忽略。这个是mysql库内部的log日志，如果觉得烦，想去掉，需要在编译时，进mysql包的源码里注释掉对应代码

**Comment by teamtopkarl** [comment]
OK

**Comment by AdminPoker** [comment]
报错后，好像口令扫描不出来。
<img width="1310" alt="图片" src="https://user-images.githubusercontent.com/51812136/171394451-b5533d51-6221-4982-8096-b833365189da.png">
<img width="1126" alt="图片" src="https://user-images.githubusercontent.com/51812136/171394918-dd049ab8-2618-498d-bd98-b9635258c0cb.png">

<img width="844" alt="图片" src="https://user-images.githubusercontent.com/51812136/171394757-80bba789-aafe-4ccd-afe1-d586b641629f.png">
