### ISSUE TITLE
有时候无法保存文件

### ISSUE THREAD

**Issue by Black-Horse-Git** [shadow1ng/fscan#142]
有时候运行不会默认产生result文件，使用-o参数也不会产生文件，很早之前发现的问题，之后没在遇到过，今天又遇到了，win linux 均遇到过，今天遇到的是Linux 的环境，且之前的扫描都成果生成文件了

**Comment by shadow1ng** [comment]
有时候生成失败可以用 fscan xxx >1.txt  试试

**Comment by shadow1ng** [comment]
然后我把生成0777->0666试试

**Comment by Black-Horse-Git** [comment]
感谢
