### ISSUE TITLE
主机发现使用icmp扫描ip不准确

### ISSUE THREAD

**Issue by fandazhou123** [shadow1ng/fscan#146]
主机发现的时候，icmp扫描不出来的地址（tcp可以扫到），对应主机在端口扫描的端口也扫不到。另外，麻烦看一下邮箱谢谢

**Comment by shadow1ng** [comment]
师傅的邮箱是不是有点问题？发邮件发不过去
![image](https://user-images.githubusercontent.com/39651966/157158969-bc1889a0-dee2-4f97-8eab-450aaba3a377.png)

**Comment by fandazhou123** [comment]
chuzongjuan@163.com 我的邮件地址是这个
