### ISSUE TITLE
无法正常扫描端口

### ISSUE THREAD

**Issue by Tim1995** [shadow1ng/fscan#147]
在Mac下进行编译出可执行文件，但是无法正常的扫描出端口的开放情况；
在Windows下，直接使用了github中编译好的exe文件去扫描IP，线程放的很高基本都可以正常扫描；
请问一下，在编译为可执行文件的时候，是否已经去进行了线程和超时等配置的调试，谢谢

**Comment by shadow1ng** [comment]
参数初始化在 common/flag.go
默认是600线程，端口扫描超时是3秒
