### ISSUE TITLE
能否支持从文件中读取ip:port这种形式的扫描呢

### ISSUE THREAD

**Issue by handbye** [shadow1ng/fscan#149]

**Comment by shadow1ng** [comment]
然后就跳过端口扫描，直接扫漏洞或web？

**Comment by shadow1ng** [comment]
能说下完整需求嘛

**Comment by handbye** [comment]
就是文件中有这类的资产
```txt
192.168.1.2:9004
192.168.1.2:8453
192.168.10.2:8433
```
读取到ip和端口的对应关系后，就直接扫描此ip对应的此端口，不再去扫其他端口了。

**Comment by tarihub** [comment]
+1 顺便 mark

**Comment by tarihub** [comment]
不过不知能否支持 hostname 的形式，就不是  ip:port ，比如有的时候需要批量把 主机名:端口 放到一个文件去扫。我试了下，是扫不出东西的。比如

hosts.txt 内容
```
localhost:80
```

./fscan -hf ./hosts.txt
输出
```
___                              _    
  / _ \     ___  ___ _ __ __ _  ___| | __ 
 / /_\/____/ __|/ __| '__/ _` |/ __| |/ /
/ /_\\_____\__ \ (__| | | (_| | (__|   <    
\____/     |___/\___|_|  \__,_|\___|_|\_\   
                     fscan version: 1.8.2
start infoscan
[*] AlivePorts len is: 1
start vulscan
已完成 1/1
[*] 扫描结束,耗时: 74.821809ms
```

**Comment by handbye** [comment]
感谢 @tarihub

**Comment by tarihub** [comment]
> 不过不知能否支持 hostname 的形式，就不是 ip:port ，比如有的时候需要批量把 主机名:端口 放到一个文件去扫。我试了下，是扫不出东西的。比如
> 
> hosts.txt 内容
> 
> ```
> localhost:80
> ```
> 
> ./fscan -hf ./hosts.txt 输出
> 
> ```
> ___                              _    
>   / _ \     ___  ___ _ __ __ _  ___| | __ 
>  / /_\/____/ __|/ __| '__/ _` |/ __| |/ /
> / /_\\_____\__ \ (__| | | (_| | (__|   <    
> \____/     |___/\___|_|  \__,_|\___|_|\_\   
>                      fscan version: 1.8.2
> start infoscan
> [*] AlivePorts len is: 1
> start vulscan
> 已完成 1/1
> [*] 扫描结束,耗时: 74.821809ms
> ```

当然 扫 ip:port 是正常的
```
./fscan -hf ./hosts.txt

   ___                              _    
  / _ \     ___  ___ _ __ __ _  ___| | __ 
 / /_\/____/ __|/ __| '__/ _` |/ __| |/ /
/ /_\\_____\__ \ (__| | | (_| | (__|   <    
\____/     |___/\___|_|  \__,_|\___|_|\_\   
                     fscan version: 1.8.2
start infoscan
[*] AlivePorts len is: 1
start vulscan
[*] WebTitle: http://127.0.0.1       code:200 len:3245  title:xxxxx
已完成 1/1
[*] 扫描结束,耗时: 16.047081902s
```
