### ISSUE TITLE
如果想扫描ip.txt列表里面的1433结果如何设置

### ISSUE THREAD

**Issue by ttsite** [shadow1ng/fscan#150]
ip.txt里面放好已经扫描的开放1433端口的ip。如何完整调用外部字典进行破解。完整格式是什么。试了几个格式怎么不行呢
fscan64.exe -hf ip.txt --userf user.txt -pwdf pass.txt -pa 1433 -t 200 -o ok.txt
上面这也哪里错了

**Comment by shadow1ng** [comment]
-pa 1433改成-p 1433

**Comment by shadow1ng** [comment]
fscan64.exe -hf ip.txt -userf user.txt -pwdf pass.txt -p 1433 -t 200 -o ok.txt

**Comment by shadow1ng** [comment]
--userf 改成-userf

**Comment by ttsite** [comment]
谢谢!
