### ISSUE TITLE
有很多扫描没有正常进行

### ISSUE THREAD

**Issue by cwkiller** [shadow1ng/fscan#16]
先使用 ./fscan -h 10.9.54.1/24
10.9.54.4:22 open
10.9.54.4:8089 open
10.9.54.8:22 open
10.9.54.12:22 open
10.9.54.8:3306 open
10.9.54.6:22 open
10.9.54.5:22 open
10.9.54.8:6379 open
10.9.54.13:22 open
10.9.54.10:22 open
10.9.54.2:80 open
10.9.54.2:8080 open
10.9.54.10:3306 open
10.9.54.10:80 open
10.9.54.8:27017 open
10.9.54.254:22 open
10.9.54.2:11211 open
10.9.54.8:9200 open
10.9.54.8:11211 open
10.9.54.5:8080 open
10.9.54.6:8089 open
10.9.54.9:22 open
10.9.54.7:22 open
10.9.54.9:8080 open
10.9.54.2:8089 open
然后使用./fscan -h 10.9.54.1/16
10.9.3.13:21 open
10.9.2.11:22 open
10.9.3.13:22 open
10.9.3.13:80 open
10.9.2.11:80 open
10.9.3.13:443 open
10.9.2.5:22 open
10.9.3.13:3306 open
10.9.2.5:80 open
10.9.2.16:22 open
10.9.3.13:5432 open
10.9.2.11:443 open
10.9.2.5:443 open
10.9.3.5:22 open
10.9.2.12:22 open
10.9.2.2:22 open
10.9.2.2:80 open
10.9.3.4:22 open
10.9.2.4:22 open
10.9.2.2:443 open
10.9.2.3:80 open
10.9.2.3:443 open
10.9.2.12:443 open
10.9.3.13:8000 open
10.9.3.3:22 open
10.9.2.12:80 open
10.9.2.3:22 open
10.9.2.4:80 open
10.9.2.4:443 open
10.9.3.3:8080 open
10.9.3.10:80 open
10.9.3.10:443 open
10.9.3.10:21 open
10.9.3.10:22 open
10.9.3.10:3306 open
10.9.3.10:5432 open
10.9.3.10:8000 open
10.9.11.3:443 open
10.9.11.3:80 open
10.9.11.2:443 open
10.9.11.2:80 open
10.9.11.1:443 open
10.9.3.2:22 open
10.9.3.1:22 open
10.9.11.5:22 open
10.9.3.254:22 open
10.9.8.2:22 open
10.9.2.13:22 open
10.9.2.13:80 open
10.9.2.13:443 open
10.9.2.250:22 open
10.9.11.1:80 open
10.9.3.1:8080 open
有很多段并没有扫就结束了
使用-hf也是一样，后面发现只要扫描ip数量过大就会出现这种情况

**Comment by shadow1ng** [comment]
因为扫B段时，默认icmp线程是3W，可能会导致漏报，所以可以使用-it 3000或者-np来减少漏报。我在想有没有更好的icmp发包方法

**Comment by shadow1ng** [comment]
默认线程已修改为1100，防止B段跑太快。回头再想想有没有更好的发包方式了

**Comment by shadow1ng** [comment]
已更换icmp 发包方式，更适合大规模发包，对该问题应该能缓解不少了
