### ISSUE TITLE
运行报错 Bug

### ISSUE THREAD

**Issue by Deep0** [shadow1ng/fscan#160]
<img width="421" alt="图片" src="https://user-images.githubusercontent.com/25843151/164459049-51d4c341-2481-488e-9130-2dc1ea3decac.png">
不知道什么原因

**Comment by shadow1ng** [comment]
我跑本地c段，没复现出来

**Comment by shadow1ng** [comment]
师傅后续还遇到这种情况嘛

**Comment by Deep0** [comment]
没再遇到。
