### ISSUE TITLE
添加域名的方式也是可以进行扫描漏洞

### ISSUE THREAD

**Issue by 12dstad2edgdsa** [shadow1ng/fscan#162]
添加域名的方式也是可以进行扫描漏洞

**Comment by shadow1ng** [comment]
师傅想表达啥？

**Comment by 12dstad2edgdsa** [comment]
批量域名探测扫描,不要只局限于网段
















在 2022-04-26 16:49:54，"影舞者" ***@***.***> 写道：

师傅想表达啥？
