### ISSUE TITLE
无存活主机或无信息的时候-o参数不会输出文件

### ISSUE THREAD

**Issue by okadwin** [shadow1ng/fscan#167]
比如扫描一个或一些目标，这些主机都没有存活，那么实际上“没有存活主机”是一个扫描结果，但是在这种情况下实际上-o参数不会创建结果文件。
这在将fscan整合到一些工具的时候可能会遇到一些麻烦，希望可以至少输出一个空文件，或无存活主机/无信息的结果提示。
另外其实结果文件希望可以稍微格式化一下，目前对结果文件没有格式说明，只能看源码去解析，并且实际上结果文件的输出也并不是固定格式，实际解析起来也有点麻烦。

**Comment by shadow1ng** [comment]
https://github.com/ZororoZ/fscanOutput
