### ISSUE TITLE
21端口ftp会卡住

### ISSUE THREAD

**Issue by Priest-Halo** [shadow1ng/fscan#175]
师傅，为啥我挂代理时程序已经开始扫描其他漏洞时，还有一部分21端口会维持连接，并且无发包也无收包，且爆破21端口时似乎很慢，希望师傅能排查一下原因
`命令：fscan.exe -h xxx.xxx.xxx.1/24 -np -num 10 -t 40 `
如图
![6YER566LTMN4WQ 8~X`DMX](https://user-images.githubusercontent.com/62275582/169213007-82438437-053d-48e1-b51a-72d9b312a213.png)

**Comment by shadow1ng** [comment]
可能有些端口开了21但不是ftp
