### ISSUE TITLE
在登录VPN的情况下扫描问题

### ISSUE THREAD

**Issue by codeyso** [shadow1ng/fscan#181]
在本机登录VPN后扫描，扫描结束后会出现vpn程序异常情况，无法正常使用。

**Comment by shadow1ng** [comment]
有什么修复建议嘛

**Comment by lapalipi** [comment]
> 有什么修复建议嘛

加个参数，指定网卡。

**Comment by codeyso** [comment]
暂时也不太清楚问题原因，VPN接入是代理模式，不会创建新网卡。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shadow1ng/fscan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月4日(星期一) 中午11:14
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [shadow1ng/fscan] 在登录VPN的情况下扫描问题 (Issue #181)





  
有什么修复建议嘛
  
加个参数，指定网卡。
