### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by invoke888** [shadow1ng/fscan#193]
[*] Icmp alive hosts len is: 43443
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0xc6cd39, 0xfe8c00000})
        runtime/panic.go:1198 +0x71
runtime.sysMap(0xc007c00000, 0x429600, 0xc000691e90)
        runtime/mem_linux.go:169 +0x96
runtime.(*mheap).grow(0x19942c0, 0x7f45c1)
        runtime/mheap.go:1393 +0x225
runtime.(*mheap).allocSpan(0x19942c0, 0x7f45c1, 0x0, 0x0)
        runtime/mheap.go:1179 +0x165
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:913 +0x69
runtime.systemstack()
        runtime/asm_amd64.s:383 +0x49

goroutine 1 [running]:
runtime.systemstack_switch()
        runtime/asm_amd64.s:350 fp=0xc00010d7f8 sp=0xc00010d7f0 pc=0x460b80
runtime.(*mheap).alloc(0xfe8b82000, 0x7f45c1, 0x0, 0x1)
        runtime/mheap.go:907 +0x73 fp=0xc00010d848 sp=0xc00010d7f8 pc=0x425933
runtime.(*mcache).allocLarge(0x7fc7fcad97d0, 0xfe8b81738, 0x60, 0x0)
        runtime/mcache.go:227 +0x89 fp=0xc00010d8a8 sp=0xc00010d848 pc=0x4165a9
runtime.mallocgc(0xfe8b81738, 0xbaad20, 0x1)
        runtime/malloc.go:1082 +0x5c5 fp=0xc00010d928 sp=0xc00010d8a8 pc=0x40cb25
runtime.makechan(0x0, 0xa9b2564d)
        runtime/chan.go:106 +0xe5 fp=0xc00010d968 sp=0xc00010d928 pc=0x405005
github.com/shadow1ng/fscan/Plugins.PortScan({0xc002198000, 0xa9b3, 0xc00010dd70}, {0x7fffbc22d2f5, 0x7}, 0x3)
        github.com/shadow1ng/fscan/Plugins/portscan.go:39 +0x2f4 fp=0xc00010db58 sp=0xc00010d968 pc=0xad33f4
github.com/shadow1ng/fscan/Plugins.Scan({{0x7fffbc22d2e6, 0xb}, {0x7fffbc22d2f5, 0x7}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...})
        github.com/shadow1ng/fscan/Plugins/scanner.go:37 +0x2d2 fp=0xc00010de40 sp=0xc00010db58 pc=0xad9632
main.main()
        github.com/shadow1ng/fscan/main.go:15 +0x98 fp=0xc00010df80 sp=0xc00010de40 pc=0xadfad8
runtime.main()
        runtime/proc.go:255 +0x227 fp=0xc00010dfe0 sp=0xc00010df80 pc=0x435be7
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc00010dfe8 sp=0xc00010dfe0 pc=0x462c61

goroutine 6 [chan receive]:
github.com/shadow1ng/fscan/common.SaveLog()
        github.com/shadow1ng/fscan/common/log.go:32 +0x54
created by github.com/shadow1ng/fscan/common.init.0
        github.com/shadow1ng/fscan/common/log.go:22 +0x25

**Comment by shadow1ng** [comment]
[*] Icmp alive hosts len is: 43443  。可能扫的IP太多，撑不住，建议分段扫扫试试
