### ISSUE TITLE
1.7.1版本  -h参数不支持域名扫描，应该是个人电脑问题，想问一下大佬如何排查

### ISSUE THREAD

**Issue by yanruo18** [shadow1ng/fscan#194]
应该是我电脑问题，-h 以及-hf不支持域名扫描，想问一下师傅如何排查。
![image](https://user-images.githubusercontent.com/57283667/175855905-a31b768c-b7cc-4d77-b900-3414ad6e2fac.png)
![image](https://user-images.githubusercontent.com/57283667/175855965-17299740-969d-4e37-9e22-e27a2dd9bbf1.png)

**Comment by shadow1ng** [comment]
-h www.baidu.com -ping 可以。默认icmp发包模式只支持ip，所以用-np或-ping都可以。
或者使用-u www.baidu.com

**Comment by yanruo18** [comment]
> 好的，谢谢大佬。感谢

**Comment by yanruo18** [comment]
谢谢大佬的解答，感谢
