### ISSUE TITLE
群主大大可以拉我进群吗？

### ISSUE THREAD

**Issue by wxx0105** [shadow1ng/fscan#196]
求入群！

**Comment by shadow1ng** [comment]
![image](https://user-images.githubusercontent.com/39651966/176338178-17c610e9-f741-4b6f-8980-cad952dda977.png)

**Comment by wxx0105** [comment]
我看到了这个，已经满了200人，需要成员邀请，不知道作者大大可否发一下微信号，我加你微信拉我进呢

**Comment by shadow1ng** [comment]
shadow1ng

**Comment by wxx0105** [comment]
感谢，已经添加
