### ISSUE TITLE
1.8.0版本-h默认不会调用除存活探测外的其他模块

### ISSUE THREAD

**Issue by nevermo0re** [shadow1ng/fscan#198]
>
![1](https://user-images.githubusercontent.com/107986035/177069247-22cade8d-7dec-4a6b-a4ce-4571c89f4217.png)

**Comment by shadow1ng** [comment]
没扫出端口吧

**Comment by nevermo0re** [comment]
截图里面都是同一个IP，至少3389是开启的

**Comment by shadow1ng** [comment]
默认不扫3389，怕爆破后，把别人挤掉线

**Comment by nevermo0re** [comment]
> 默认不扫3389，怕爆破后，把别人挤掉线

了解了，问题终结，谢谢
