### ISSUE TITLE
新版本与老版本扫描结果差异较大

### ISSUE THREAD

**Issue by lapalipi** [shadow1ng/fscan#199]
环境：Mac、同一局域网、扫描内网C段。
使用了老版本的fscan扫描的结果，直接-h
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/66582830/177075143-c8106303-d13a-44a3-8359-658b004e75b5.png">

同样新版本-h扫描：
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/66582830/177074937-2b3ccc8d-84ad-48e8-a694-7e407d5ba3a6.png">

想问下大佬，这是什么原因造成的？

**Comment by shadow1ng** [comment]
sudo试试？icmp模块权限不足
