### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by wuha0926** [shadow1ng/fscan#205]
![image](https://user-images.githubusercontent.com/55070619/177667088-ba26d28c-029f-4c9e-8a43-f05ce60d837b.png)

**Comment by xiyang2011** [comment]
common\flag.go 文件加入包
"time"
"runtime"
"runtime/debug"
在WebScan\lib\eval.go文件加入包
"github.com/shadow1ng/fscan/common"

**Comment by Teicu** [comment]
same here  ( Mac OS )

<img width="470" alt="Screenshot 2022-07-07 at 10 03 59" src="https://user-images.githubusercontent.com/1572822/177712394-0f617b1d-e640-4e42-ac61-62b8895eca0e.png">

**Comment by shadow1ng** [comment]
好了，更新上去了，golang 提交代码时，没自动提交这几行代码

**Comment by Teicu** [comment]
> Ok, the update is up. When golang submitted the code, it did not automatically submit these lines of code

By the way, please tell me the best way to install it in Mac? Thank you very much

**Comment by Teicu** [comment]
> Ok, the update is up. When golang submitted the code, it did not automatically submit these lines of code

works fine now! Thanks again
