### ISSUE TITLE
M1芯片的MacOS 运行错误

### ISSUE THREAD

**Issue by TaoKe-One** [shadow1ng/fscan#207]
麻烦在readme加一个Mac的使用方法，我在下载后没办法运行。

**Comment by TaoKe-One** [comment]
<img width="457" alt="image" src="https://user-images.githubusercontent.com/65479877/177940482-8ba6ed3a-223a-497b-86f6-b4c8b067af5a.png">

**Comment by shadow1ng** [comment]
https://github.com/shadow1ng/fscan/blob/45008bcbfc8f540ff78584983002ac77097ce262/README.md?plain=1#L62

**Comment by TaoKe-One** [comment]
可以了谢谢，非常棒

**Comment by psl-b** [comment]
@TaoKe-One   大哥会在m1mac上运行fscan啊 真的哭了 编译好多报错  教教我好吗 有偿 呜呜

**Comment by TaoKe-One** [comment]
@psl-b 你使用go build -ldflags="-s -w " -trimpath main.go 这条命令编译完不是生成一个main的文件嘛，直接在命令行运行正常命令就行了呀，参数你自己看它的介绍就可以了

**Comment by TaoKe-One** [comment]
@psl-b 我建议你在编译的时候终端挂上代理，然后再去编译，不然它有些组件需要翻墙，你会获取超时。

**Comment by psl-b** [comment]
@TaoKe-One  不是呀 我编译的时候他直接报错
<img width="731" alt="error" src="https://user-images.githubusercontent.com/109031584/178149769-14b9d938-b201-49fa-bf18-a0adb9362aae.png">
了

**Comment by psl-b** [comment]
@TaoKe-One 你是我大哥。能加个qq（3070942735）教教我吗 呜呜

**Comment by shadow1ng** [comment]
git clone 下载最新代码试试

**Comment by MingKoo** [comment]
> @TaoKe-One 不是呀 我编译的时候他直接报错
> <img alt="error" width="731" src="https://user-images.githubusercontent.com/109031584/178149769-14b9d938-b201-49fa-bf18-a0adb9362aae.png">
> 了

安装好GO环境，其中最容易出错的是：export GOTPAHT = {源代码路径，src的上一级文件夹}
编译命令（打开科学上网）进行
go build -ldflags="-s -w " -trimpath main.go
如果编译发现错误：
go: github.com/denisenkom/go-mssqldb@v0.11.0: Get "https://proxy.golang.org/github.com/denisenkom/go-mssqldb/@v/v0.11.0.mod": dial tcp 142.251.42.241:443: i/o timeout
解决：
go env -w GOSUMDB=off
go env -w GOPROXY=https://goproxy.cn,direct/
再次执行编译，会生成一个main。这个main即查fscan可执行文件。
