### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 0xa-saline** [shadow1ng/fscan#21]
编译了一个，在内网测试的是报错了
![image](https://user-images.githubusercontent.com/14137698/104126188-2cfe5f80-5396-11eb-8184-874068d6e716.png)

panic: reflect: call of reflect.Value.Type on zero Value

goroutine 209696 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x4, 0x221a2a0)
        c:/go/src/reflect/value.go:1908 +0x13e
github.com/shadow1ng/fscan/Plugins.ScanFunc(0x1434c000, 0x148c09cd, 0x4, 0x15664
fbc, 0x1, 0x1, 0x0, 0x138173d, 0x1d651ec, 0x14026100, ...)
        C:/source/fscan-main/Plugins/scanner.go:75 +0xbb
github.com/shadow1ng/fscan/Plugins.AddScan.func1(0x148c09cd, 0x4, 0x14baeb40, 0x
140e45f0, 0x14a6e3c0)
        C:/source/fscan-main/Plugins/scanner.go:58 +0x71
created by github.com/shadow1ng/fscan/Plugins.AddScan
        C:/source/fscan-main/Plugins/scanner.go:57 +0x9d

**Comment by shadow1ng** [comment]
请问是用什么命令运行的？  然后是用什么版本的golang编译的？

**Comment by shadow1ng** [comment]
看起来是反射调用函数时产生的错误，用已编译好的，是否运行正常呢

**Comment by 0xa-saline** [comment]
1.6编译的。用编译好的1.4版本可以跑的.

**Comment by shadow1ng** [comment]
我并不知道你的运行参数，看起来是反射调用函数时产生的错误，可以看看PluginList有没有对应的参数的值吧。
