### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by fengx1a0** [shadow1ng/fscan#213]
# ./fscan_amd64 -hf pool.txt -nopoc -nobr -np -o results.txt
   ___                              _    
  / _ \     ___  ___ _ __ __ _  ___| | __ 
 / /_\/____/ __|/ __| '__/ _` |/ __| |/ /
/ /_\\_____\__ \ (__| | | (_| | (__|   <    
\____/     |___/\___|_|  \__,_|\___|_|\_\   
                     fscan version: 1.8.1
start infoscan
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0xc602a5, 0x14ebc00000})
	runtime/panic.go:1198 +0x71
runtime.sysMap(0xc0c7400000, 0x4296e0, 0xc000661e90)
	runtime/mem_linux.go:169 +0x96
runtime.(*mheap).grow(0x19895c0, 0xa75df1)
	runtime/mheap.go:1393 +0x225
runtime.(*mheap).allocSpan(0x19895c0, 0xa75df1, 0x0, 0x0)
	runtime/mheap.go:1179 +0x165
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:913 +0x69
runtime.systemstack()
	runtime/asm_amd64.s:383 +0x49

goroutine 1 [running]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:350 fp=0xc00030d968 sp=0xc00030d960 pc=0x460d00
runtime.(*mheap).alloc(0x14ebbe2000, 0xa75df1, 0x0, 0x1)
	runtime/mheap.go:907 +0x73 fp=0xc00030d9b8 sp=0xc00030d968 pc=0x425933
runtime.(*mcache).allocLarge(0x7ff19554eec8, 0x14ebbe2000, 0x60, 0x0)
	runtime/mcache.go:227 +0x89 fp=0xc00030da18 sp=0xc00030d9b8 pc=0x4165a9
runtime.mallocgc(0x14ebbe2000, 0xb9e860, 0x1)
	runtime/malloc.go:1082 +0x5c5 fp=0xc00030da98 sp=0xc00030da18 pc=0x40cb25
runtime.makechan(0x0, 0xdf27ec00)
	runtime/chan.go:106 +0xe5 fp=0xc00030dad8 sp=0xc00030da98 pc=0x405005
github.com/shadow1ng/fscan/Plugins.PortScan({0xc039380000, 0x1060e00, 0x7ffdc83c37f6}, {0xc0001e0480, 0x45c}, 0x3)
	github.com/shadow1ng/fscan/Plugins/portscan.go:39 +0x2f4 fp=0xc00030dcc8 sp=0xc00030dad8 pc=0xac6db4
github.com/shadow1ng/fscan/Plugins.Scan({{0x0, 0x0}, {0xc0001e0480, 0x45c}, {0x0, 0x0}, {0x0, 0x0, 0x0}})
	github.com/shadow1ng/fscan/Plugins/scanner.go:37 +0x310 fp=0xc00030def8 sp=0xc00030dcc8 pc=0xacd010
main.main()
	github.com/shadow1ng/fscan/main.go:14 +0x85 fp=0xc00030df80 sp=0xc00030def8 pc=0xad3545
runtime.main()
	runtime/proc.go:255 +0x227 fp=0xc00030dfe0 sp=0xc00030df80 pc=0x435cc7
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc00030dfe8 sp=0xc00030dfe0 pc=0x462de1

goroutine 6 [sleep]:
time.Sleep(0x2540be400)
	runtime/time.go:193 +0x12e
github.com/shadow1ng/fscan/common.init.0.func1()
	github.com/shadow1ng/fscan/common/flag.go:15 +0x2e
created by github.com/shadow1ng/fscan/common.init.0
	github.com/shadow1ng/fscan/common/flag.go:11 +0x25

goroutine 7 [chan receive]:
github.com/shadow1ng/fscan/common.SaveLog()
	github.com/shadow1ng/fscan/common/log.go:32 +0x54
created by github.com/shadow1ng/fscan/common.init.1
	github.com/shadow1ng/fscan/common/log.go:22 +0x25

**Comment by shadow1ng** [comment]
师傅是扫了多少个Ip?
