### ISSUE TITLE
socks5

### ISSUE THREAD

**Issue by 23jdn** [shadow1ng/fscan#217]
socks5代理下如何正常内网扫描

**Comment by 23jdn** [comment]
socks proxifier 下 fscan64.exe -h 192.168.50.1/24 -np 扫描显示整个c段端口全开

**Comment by shadow1ng** [comment]
我之前win+frp+proxifier 下正常。
师傅可以试试别的工具也这样嘛。也有其他人反应这个问题，但别的工具也是端口全开

**Comment by SnowMeteors** [comment]
Stowaway开启socks5，fscan走proxifier无法成功探测内网

**Comment by shadow1ng** [comment]
-np



发自我的iPhone


------------------ Original ------------------
From: 麦当 ***@***.***&gt;
Date: Fri,Sep 16,2022 8:47 PM
To: shadow1ng/fscan ***@***.***&gt;
Cc: 影舞者 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [shadow1ng/fscan] socks5 (Issue #217)





 
Stowaway开启socks5，fscan走proxifier无法成功探测内网

**Comment by SnowMeteors** [comment]
> -np 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: 麦当 ***@***.***&gt; Date: Fri,Sep 16,2022 8:47 PM To: shadow1ng/fscan ***@***.***&gt; Cc: 影舞者 ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [shadow1ng/fscan] socks5 (Issue #217) Stowaway开启socks5，fscan走proxifier无法成功探测内网 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你可能不相信，加入np后，机子直接卡死了。。。。

**Comment by SnowMeteors** [comment]
我看到最新版的fscan支持socks5了，请问socks5的格式怎么输入，是这样吗 -socks5 socks5://127.0.0.1:1555

**Comment by SnowMeteors** [comment]
> -np 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: 麦当 ***@***.***&gt; Date: Fri,Sep 16,2022 8:47 PM To: shadow1ng/fscan ***@***.***&gt; Cc: 影舞者 ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [shadow1ng/fscan] socks5 (Issue #217) Stowaway开启socks5，fscan走proxifier无法成功探测内网 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

感谢，已解决
