### ISSUE TITLE
ubuntu编译时遇到个奇怪的问题，求帮助

### ISSUE THREAD

**Issue by dolo** [shadow1ng/fscan#220]
~/tools/fscan$ go build -ldflags="-s -w " -trimpath main.go
flag provided but not defined: -trimpath
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.

**Comment by shadow1ng** [comment]
go版本问题

**Comment by dolo** [comment]
> go版本问题

感谢，ubuntu18 apt-get的是1.10，会报这个错误。从官网下载了最新的1.19后，编译成功了！
