### ISSUE TITLE
火绒会报病毒

### ISSUE THREAD

**Issue by Hambing** [shadow1ng/fscan#223]
病毒名称：Trojan/Generic!D66C4A61C335BF75
病毒ID：D66C4A61C335BF75
下载的最新release版本，64位。

**Comment by shadow1ng** [comment]
火绒会杀黑客工具。怕被杀可自行编译、免杀调试

**Comment by goldroad** [comment]
不仅火绒，谷歌浏览器、Windows都会拦截

**Comment by shadow1ng** [comment]
对于杀软来说，属于黑客工具，被杀很正常。frp、mimika也被杀
