### ISSUE TITLE
最新版本火绒报毒，奇安信检测高威胁

### ISSUE THREAD

**Issue by half-nothing** [shadow1ng/fscan#226]
如题
![image](https://user-images.githubusercontent.com/50048293/188802998-02aef5c6-3301-4077-8878-e5e29de7b62d.png)
奇安信连接
https://sandbox.ti.qianxin.com/sandbox/page/detail?type=file&id=AYMWl5WTa5r8RybxX333&env=&time=&sha1=0f53892c43ccc3f64c524f7b04ab914123e36d48

**Comment by shadow1ng** [comment]
正常，已被大部分杀软针对。源码都有了，自己编译、做做免杀就行

**Comment by spac3wh1te** [comment]
> 正常，已被大部分杀软针对。源码都有了，自己编译、做做免杀就行

自己编译的时候出现rdp模块的报错，请问作者是怎么解决的呢？
