### ISSUE TITLE
这里漏了返回？

### ISSUE THREAD

**Issue by xiyang2011** [shadow1ng/fscan#238]
https://github.com/shadow1ng/fscan/blob/38e48ba4205196e042db8f832a7789b76ee61c5e/Plugins/webtitle.go#L209

**Comment by shadow1ng** [comment]
函数末尾return返回title,有啥问题嘛

**Comment by xiyang2011** [comment]
漏了参数title

**Comment by shadow1ng** [comment]
不需要啊。。。  定义函数的时候已经定义了返回变量
func gettitle(body []byte) (title string)

**Comment by xiyang2011** [comment]
不好意思哈，刚学不久，忘记还有这种写法
