### ISSUE TITLE
协议探测建议

### ISSUE THREAD

**Issue by wuxiaodai** [shadow1ng/fscan#24]
增加基于tcp的协议探测。

**Comment by shadow1ng** [comment]
现在端口扫描是基于tcp协议的。你说的协议探测是指的什么方面的？

**Comment by wuxiaodai** [comment]
如果ip禁ping了，还能探测吗，大佬带带我



---原始邮件---
发件人: "影舞者"<notifications@github.com&gt;
发送时间: 2021年2月4日(周四) 下午2:32
收件人: "shadow1ng/fscan"<fscan@noreply.github.com&gt;;
抄送: "xiaodai"<1903250245@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [shadow1ng/fscan] 协议探测建议 (#24)




 
现在端口扫描是基于tcp协议的。你说的协议探测是指的什么方面的？

**Comment by shadow1ng** [comment]
-np 参数跳过ping探测
fscan -h xxx -np

**Comment by wuxiaodai** [comment]
大佬大佬，收到

---原始邮件---
发件人: "影舞者"<notifications@github.com&gt;
发送时间: 2021年2月4日(周四) 下午3:06
收件人: "shadow1ng/fscan"<fscan@noreply.github.com&gt;;
抄送: "xiaodai"<1903250245@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [shadow1ng/fscan] 协议探测建议 (#24)




 
-np 参数跳过ping探测
 fscan -h xxx -np
