### ISSUE TITLE
二进制与编译出现点问题

### ISSUE THREAD

**Issue by CyanogenCyanogen** [shadow1ng/fscan#241]
最近手残更新了ventura 13.0后，想把fscan也更新到1.8（原来使用1.6，编译成功）

使用编译后二进制包，提示出现问题：
root@cyan Downloads # shasum fscan_darwin 
ec194ae1f959f9f3fd28950e4289fe836ccb6cd2  fscan_darwin
root@cyan Downloads # ./fscan_darwin 
zsh: segmentation fault  ./fscan_darwin

想着可能是自己把环境搞烂的原因，使用编译，发现以下报错：
root@cyan fscan # go build -ldflags="-s -w " -trimpath main.go 
# github.com/sijms/go-ora/v2
vendor/github.com/sijms/go-ora/v2/parameter.go:393:7: undefined: sql.NullByte
vendor/github.com/sijms/go-ora/v2/parameter.go:405:7: undefined: sql.NullInt16
vendor/github.com/sijms/go-ora/v2/parameter.go:465:8: undefined: sql.NullByte
vendor/github.com/sijms/go-ora/v2/parameter.go:482:8: undefined: sql.NullInt16
vendor/github.com/sijms/go-ora/v2/parameter_decode_array.go:32:9: undefined: sql.NullInt16
vendor/github.com/sijms/go-ora/v2/parameter_decode_array.go:45:10: undefined: sql.NullInt16
vendor/github.com/sijms/go-ora/v2/parameter_decode_array.go:378:9: undefined: sql.NullByte
vendor/github.com/sijms/go-ora/v2/parameter_decode_array.go:391:10: undefined: sql.NullByte
vendor/github.com/sijms/go-ora/v2/parameter_encode_array.go:76:81: undefined: sql.NullByte
vendor/github.com/sijms/go-ora/v2/parameter_encode_array.go:93:82: undefined: sql.NullInt16
vendor/github.com/sijms/go-ora/v2/parameter_decode_array.go:391:10: too many errors

已尝试清除go缓存，爬梯子拉去插件，但是无效
师傅们看看是发现什么问题，谢谢师傅们

**Comment by shadow1ng** [comment]
更新go 版本试试

**Comment by CyanogenCyanogen** [comment]
好的，我试试

**Comment by CyanogenCyanogen** [comment]
感谢，已经解决，是go版本问题
