### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by chenchenhen6** [shadow1ng/fscan#246]
师傅，我直接下载git源码，编译失败
go run main.go -h
提示
go: updates to go.mod needed; to update it:
	go mod tidy
然后我又运行go mod tidy
再次编译提示
# github.com/shadow1ng/fscan/Plugins
Plugins/base.go:54:14: undefined: aes
Plugins/base.go:60:15: undefined: cipher
Plugins/base.go:65:9: undefined: base64
Plugins/base.go:69:19: undefined: base64
Plugins/base.go:72:14: undefined: aes
Plugins/base.go:76:15: undefined: cipher
Plugins/base.go:90:13: undefined: bytes

**Comment by shadow1ng** [comment]
再试试？更新了

**Comment by chenchenhen6** [comment]
好嘞

**Comment by chenchenhen6** [comment]
解决了，感谢师傅

**Comment by chenchenhen6** [comment]
师傅，我编译出来发现扫描默认生成的result.txt不是在当前目录下，而是在当前目录的上一层

**Comment by shadow1ng** [comment]
更新代码了，再试试

**Comment by chenchenhen6** [comment]
好了好了，大佬
