### ISSUE TITLE
程序自己崩溃，无法找到原因

### ISSUE THREAD

**Issue by Sexisnull** [shadow1ng/fscan#249]
在扫描大范围ip时，程序总会莫名其妙的自己停止，并提示已杀死。请问这种错误如何排查？
<img width="518" alt="image" src="https://user-images.githubusercontent.com/38177084/204958091-10215a08-e855-4ea8-982d-2716d48bc755.png">

**Comment by shadow1ng** [comment]
会不会是内存满了

**Comment by Sexisnull** [comment]
应该不是，希望能添加程序运行log，帮助排查错误
