### ISSUE TITLE
自行编译失败 undefined: getpath

### ISSUE THREAD

**Issue by flower-King** [shadow1ng/fscan#250]
user@HP-Linux:~/下载/fscan$ go build -ldflags="-s -w " -trimpath ./main.go

\#github.com/shadow1ng/fscan/common
common/Parse.go:10:2: imported and not used: "os/exec"
common/Parse.go:11:2: imported and not used: "path/filepath"
common/Parse.go:142:17: undefined: getpath

go 版本：go version go1.19.3 linux/amd64

**Comment by shadow1ng** [comment]
重新git clone一下源码
