### ISSUE TITLE
求助,编译报错

### ISSUE THREAD

**Issue by Cong-Ma** [shadow1ng/fscan#258]
下面是完整的编译信息,不知道哪里出问题了

D:\fscan\fscan-main>go build -ldflags="-s -w " -trimpath main.go
go: downloading golang.org/x/net v0.0.0-20210610132358-84b48f89b13b
go: downloading github.com/shadow1ng/goWMIExec v0.0.2
go: downloading github.com/go-sql-driver/mysql v1.6.0
go: downloading github.com/denisenkom/go-mssqldb v0.12.2
go: downloading github.com/hirochachacha/go-smb2 v1.1.0
go: downloading github.com/jlaffaye/ftp v0.0.0-20220630165035-11536801d1ff
go: downloading github.com/lib/pq v1.10.6
go: downloading github.com/sijms/go-ora/v2 v2.4.28
go: downloading github.com/stacktitan/smb v0.0.0-20190531122847-da9a425dceb8
go: downloading github.com/shadow1ng/grdp v1.0.3
go: downloading golang.org/x/text v0.3.6
go: downloading golang.org/x/crypto v0.0.0-20210513164829-c07d793c2f9a
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/golang/protobuf v1.3.4
go: downloading github.com/google/cel-go v0.6.0
go: downloading github.com/satori/go.uuid v1.2.0
go: downloading google.golang.org/genproto v0.0.0-20200416231807-8751e049a2a0
go: downloading gopkg.in/yaml.v2 v2.4.0
Plugins\wmiexec.go:11:2: github.com/shadow1ng/goWMIExec@v0.0.2: Get "https://proxy.golang.org/github.com/shadow1ng/go%21w%21m%21i%21exec/@v/v0.0.2.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\mongodb.go:5:2: github.com/denisenkom/go-mssqldb@v0.12.2: Get "https://proxy.golang.org/github.com/denisenkom/go-mssqldb/@v/v0.12.2.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\mysql.go:6:2: github.com/go-sql-driver/mysql@v1.6.0: Get "https://proxy.golang.org/github.com/go-sql-driver/mysql/@v/v1.6.0.zip": dial tcp 172.217.160.81:443: i/o timeout
WebScan\lib\http.pb.go:9:2: github.com/golang/protobuf@v1.3.4: Get "https://proxy.golang.org/github.com/golang/protobuf/@v/v1.3.4.zip": dial tcp 172.217.160.81:443: i/o timeout
WebScan\lib\check.go:6:2: github.com/google/cel-go@v0.6.0: Get "https://proxy.golang.org/github.com/google/cel-go/@v/v0.6.0.zip": dial tcp 172.217.160.81:443: i/o timeout
WebScan\lib\eval.go:11:2: github.com/google/cel-go@v0.6.0: Get "https://proxy.golang.org/github.com/google/cel-go/@v/v0.6.0.zip": dial tcp 172.217.160.81:443: i/o timeout
WebScan\lib\eval.go:12:2: github.com/google/cel-go@v0.6.0: Get "https://proxy.golang.org/github.com/google/cel-go/@v/v0.6.0.zip": dial tcp 172.217.160.81:443: i/o timeout
WebScan\lib\eval.go:13:2: github.com/google/cel-go@v0.6.0: Get "https://proxy.golang.org/github.com/google/cel-go/@v/v0.6.0.zip": dial tcp 172.217.160.81:443: i/o timeout
WebScan\lib\eval.go:14:2: github.com/google/cel-go@v0.6.0: Get "https://proxy.golang.org/github.com/google/cel-go/@v/v0.6.0.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\smb2.go:11:2: github.com/hirochachacha/go-smb2@v1.1.0: Get "https://proxy.golang.org/github.com/hirochachacha/go-smb2/@v/v1.1.0.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\ftp.go:5:2: github.com/jlaffaye/ftp@v0.0.0-20220630165035-11536801d1ff: Get "https://proxy.golang.org/github.com/jlaffaye/ftp/@v/v0.0.0-20220630165035-11536801d1ff.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\postgres.go:6:2: github.com/lib/pq@v1.10.6: Get "https://proxy.golang.org/github.com/lib/pq/@v/v1.10.6.zip": dial tcp 172.217.160.81:443: i/o timeout
WebScan\lib\shiro.go:11:2: github.com/satori/go.uuid@v1.2.0: Get "https://proxy.golang.org/github.com/satori/go.uuid/@v/v1.2.0.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\oracle.go:7:2: github.com/sijms/go-ora/v2@v2.4.28: Get "https://proxy.golang.org/github.com/sijms/go-ora/v2/@v/v2.4.28.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\smb.go:7:2: github.com/stacktitan/smb@v0.0.0-20190531122847-da9a425dceb8: Get "https://proxy.golang.org/github.com/stacktitan/smb/@v/v0.0.0-20190531122847-da9a425dceb8.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\rdp.go:7:2: github.com/shadow1ng/grdp@v1.0.3: Get "https://proxy.golang.org/github.com/shadow1ng/grdp/@v/v1.0.3.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\rdp.go:8:2: github.com/shadow1ng/grdp@v1.0.3: Get "https://proxy.golang.org/github.com/shadow1ng/grdp/@v/v1.0.3.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\rdp.go:9:2: github.com/shadow1ng/grdp@v1.0.3: Get "https://proxy.golang.org/github.com/shadow1ng/grdp/@v/v1.0.3.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\rdp.go:10:2: github.com/shadow1ng/grdp@v1.0.3: Get "https://proxy.golang.org/github.com/shadow1ng/grdp/@v/v1.0.3.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\rdp.go:11:2: github.com/shadow1ng/grdp@v1.0.3: Get "https://proxy.golang.org/github.com/shadow1ng/grdp/@v/v1.0.3.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\rdp.go:12:2: github.com/shadow1ng/grdp@v1.0.3: Get "https://proxy.golang.org/github.com/shadow1ng/grdp/@v/v1.0.3.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\rdp.go:13:2: github.com/shadow1ng/grdp@v1.0.3: Get "https://proxy.golang.org/github.com/shadow1ng/grdp/@v/v1.0.3.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\rdp.go:14:2: github.com/shadow1ng/grdp@v1.0.3: Get "https://proxy.golang.org/github.com/shadow1ng/grdp/@v/v1.0.3.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\rdp.go:15:2: github.com/shadow1ng/grdp@v1.0.3: Get "https://proxy.golang.org/github.com/shadow1ng/grdp/@v/v1.0.3.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\ssh.go:7:2: golang.org/x/crypto@v0.0.0-20210513164829-c07d793c2f9a: Get "https://proxy.golang.org/golang.org/x/crypto/@v/v0.0.0-20210513164829-c07d793c2f9a.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\icmp.go:7:2: golang.org/x/net@v0.0.0-20210610132358-84b48f89b13b: Get "https://proxy.golang.org/golang.org/x/net/@v/v0.0.0-20210610132358-84b48f89b13b.zip": dial tcp 172.217.160.81:443: i/o timeout
common\proxy.go:5:2: golang.org/x/net@v0.0.0-20210610132358-84b48f89b13b: Get "https://proxy.golang.org/golang.org/x/net/@v/v0.0.0-20210610132358-84b48f89b13b.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\webtitle.go:10:2: golang.org/x/text@v0.3.6: Get "https://proxy.golang.org/golang.org/x/text/@v/v0.3.6.zip": dial tcp 172.217.160.81:443: i/o timeout
WebScan\lib\eval.go:16:2: google.golang.org/genproto@v0.0.0-20200416231807-8751e049a2a0: Get "https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20200416231807-8751e049a2a0.zip": dial tcp 172.217.160.81:443: i/o timeout
WebScan\lib\http.pb.go:10:2: gopkg.in/yaml.v2@v2.4.0: Get "https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.4.0.zip": dial tcp 172.217.160.81:443: i/o timeout
Plugins\NetBIOS.go:8:2: gopkg.in/yaml.v3@v3.0.1: Get "https://proxy.golang.org/gopkg.in/yaml.v3/@v/v3.0.1.zip": dial tcp 172.217.160.81:443: i/o timeout

**Comment by shadow1ng** [comment]
dial tcp 172.217.160.81:443: i/o timeout  网络问题
```
go env -w GOPROXY=https://goproxy.cn,direct
go mod tidy
```

**Comment by Cong-Ma** [comment]
感谢大佬.
安装好go语言的编译环境后,在main.go所在目录下,输入下面三条命令后
go env -w GOPROXY=https://goproxy.cn,direct
go mod tidy
go build -ldflags="-s -w " -trimpath main.go
会生成main.exe文件.输入命令参数即可使用
