### ISSUE TITLE
我想知道MacOS13 怎么使用

### ISSUE THREAD

**Issue by GodMQM** [shadow1ng/fscan#261]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/50479566/217748497-11fa6039-1661-4bd5-aeec-a2dea011f81c.png">

**Comment by shadow1ng** [comment]
go run main.go 能运行麻。我这边也没mac测试环境

**Comment by GodMQM** [comment]
> go run main.go 能运行麻。我这边也没有mac测试环境

重新编译一遍就可以用了

**Comment by sophomoreser** [comment]
./main -h

**Comment by Zero-GergeryHat** [comment]
解决这个问题了么，我这也有这个问题
