### ISSUE TITLE
如果要进行Windows弱密码破解是用smb模块么 

### ISSUE THREAD

**Issue by sunnoy** [shadow1ng/fscan#267]
如题

**Comment by shadow1ng** [comment]
smb smb2 rdp 都可以



------------------ 原始邮件 ------------------
发件人: sunnoy ***@***.***&gt;
发送时间: 2023年3月16日 18:19
收件人: shadow1ng/fscan ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [shadow1ng/fscan] 如果要进行Windows弱密码破解是用smb模块么  (Issue #267)





 
如题
