### ISSUE TITLE
编译完了以后运行没反应

### ISSUE THREAD

**Issue by 1y0ng** [shadow1ng/fscan#270]
大佬能帮我看一下是怎么回事吗？编译完了以后运行没反应，编译的时候也没反应
![图片](https://user-images.githubusercontent.com/112733473/235114907-87c3b9c6-b1b9-4e16-9167-0b9e61113cdf.png)

**Comment by shadow1ng** [comment]
Go run main.go有反应吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 1y0ng ***@***.***&gt;
发送时间: 2023年4月28日 17:48
收件人: shadow1ng/fscan ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [shadow1ng/fscan] 编译完了以后运行没反应 (Issue #270)





 
大佬能帮我看一下是怎么回事吗？编译完了以后运行没反应，编译的时候也没反应

**Comment by 1y0ng** [comment]
> Go run main.go有反应吗 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 1y0ng ***@***.***&gt; 发送时间: 2023年4月28日 17:48 收件人: shadow1ng/fscan ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [shadow1ng/fscan] 编译完了以后运行没反应 (Issue #270) 大佬能帮我看一下是怎么回事吗？编译完了以后运行没反应，编译的时候也没反应 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

![图片](https://user-images.githubusercontent.com/112733473/235124159-3569bf0b-e090-4b46-881f-899bc194c54e.png)

**Comment by shadow1ng** [comment]
看看杀软或者go env 确认下设置系统版本是否正确



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 1y0ng ***@***.***&gt;
发送时间: 2023年4月28日 18:29
收件人: shadow1ng/fscan ***@***.***&gt;
抄送: 影舞者 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [shadow1ng/fscan] 编译完了以后运行没反应 (Issue #270)





  
Go run main.go有反应吗 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: 1y0ng @.&gt; 发送时间: 2023年4月28日 17:48 收件人: shadow1ng/fscan @.&gt; 抄送: Subscribed @.&gt; 主题: Re: [shadow1ng/fscan] 编译完了以后运行没反应 (Issue #270) 大佬能帮我看一下是怎么回事吗？编译完了以后运行没反应，编译的时候也没反应 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;

**Comment by 1y0ng** [comment]
> 看看杀软或者go env 确认下设置系统版本是否正确 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 1y0ng ***@***.***&gt; 发送时间: 2023年4月28日 18:29 收件人: shadow1ng/fscan ***@***.***&gt; 抄送: 影舞者 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [shadow1ng/fscan] 编译完了以后运行没反应 (Issue #270) Go run main.go有反应吗 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: 1y0ng @.&gt; 发送时间: 2023年4月28日 17:48 收件人: shadow1ng/fscan @.&gt; 抄送: Subscribed @.&gt; 主题: Re: [shadow1ng/fscan] 编译完了以后运行没反应 (Issue #270) 大佬能帮我看一下是怎么回事吗？编译完了以后运行没反应，编译的时候也没反应 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

麻烦大佬帮我看一下是哪里有问题，这是我的env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\liyong12299\AppData\Local\go-build
set GOENV=C:\Users\liyong12299\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\golang\main\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\golang\main
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\GO
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLDIR=D:\GO\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=D:\edge_download\渗透工具\信息收集\fscan-main\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\LIYONG~1\AppData\Local\Temp\go-build2955749389=/tmp/go-build -gno-record-gcc-switches

**Comment by Solan999** [comment]
解决了么师傅，我的情况和你一样
