### ISSUE TITLE
纯小白，请教师傅用法

### ISSUE THREAD

**Issue by ghost** [shadow1ng/fscan#288]
下载zip解压后，要如何使用该工具呢？到这一步就不会了。
![image](https://github.com/shadow1ng/fscan/assets/105402715/09bc10cc-2438-4079-8b2b-356501e297af)

**Comment by shadow1ng** [comment]
要下载release里的exe。源码的话，要自行编译,go build main.go

**Comment by sternstundes** [comment]
建议用kali下载 搭环境也比较方便

**Comment by tp20c5** [comment]
没后缀的是给linux用的
