### ISSUE TITLE
icmp扫描模式，-o参数未支持写入文件

### ISSUE THREAD

**Issue by heroanswer** [shadow1ng/fscan#289]
扫描命令：
sudo ./fscan_darwin -h 192.168.100.1/16 -m icmp -o 16_result.txt

-o 参数未支持写入文件

fscan version: 1.6.3

**Comment by yz1639** [comment]
win下测试是正常的，你要不更新版本至最新？ 1.6.3好像很旧了 我这版本是1.8.2
![image](https://github.com/shadow1ng/fscan/assets/44149984/7611c989-0d10-4e34-a44f-15cf630d6037)
