### ISSUE TITLE
mysql 爆破存在问题

### ISSUE THREAD

**Issue by ppuuoo** [shadow1ng/fscan#291]
某次实战渗透中，发现mysql的爆破中有一个主机无法爆破成功，但是我可以使用navicat 连接

目标的mysql是5.1的，也就是说要连接的服务端mysql 5.1.60

<img width="522" alt="image" src="https://github.com/shadow1ng/fscan/assets/28812583/ec39e788-f2ac-4ec4-8860-58c769d178ab">

<img width="293" alt="image" src="https://github.com/shadow1ng/fscan/assets/28812583/f0db86b2-df5f-42da-9d2a-8c6dba88252c">
<img width="954" alt="image" src="https://github.com/shadow1ng/fscan/assets/28812583/73b0931e-53a5-4bf3-be6b-578eff1fe1a0">

fscan 没有爆破成功，我登陆了内网的一台机器，安装mysql尝试登陆

<img width="494" alt="image" src="https://github.com/shadow1ng/fscan/assets/28812583/f36f72c3-2dbe-4e96-92c0-bcea8ca6b729">

竟然也未能登了成功，查原因可能是mysql版本过低造成了的，比如说我客户端是5.7的

<img width="497" alt="image" src="https://github.com/shadow1ng/fscan/assets/28812583/97e5c56e-9c8c-4a8c-922f-6ba73d55c2a8">
<img width="769" alt="image" src="https://github.com/shadow1ng/fscan/assets/28812583/32ec78de-3d67-4523-a6fc-bbdda85818f1">
<img width="799" alt="image" src="https://github.com/shadow1ng/fscan/assets/28812583/d84f57b1-661e-4443-8a23-efcafdc3bbc9">

说是一个旧的客户端版本造成的，我的navicat的版本是16，没有问题，可以直接连接，我想可能是服务端版本太低了
我在想fscan的mysql爆破这个模块用的什么版本呢！高版本造成的吗，因为目标版本是5.1的低版本，希望能够修复此问题，属于某次爆破无意中发现。

**Comment by XiaoliChan** [comment]
开启下列应该可以，我测了5.1.73
```
		AllowNativePasswords:    true,
		AllowOldPasswords:       true,
		AllowCleartextPasswords: true,
```
