### ISSUE TITLE
MAC 13.4编译timeout 但是网络可达

### ISSUE THREAD

**Issue by NanLuF** [shadow1ng/fscan#296]
按照手册编译，会卡在
<img width="1278" alt="image" src="https://github.com/shadow1ng/fscan/assets/35839396/510978c7-563a-46ac-966f-e09ac37a4943">
但是将链接复制在浏览器中可以下载。
<img width="1346" alt="image" src="https://github.com/shadow1ng/fscan/assets/35839396/d75f4050-fa92-4fe2-add2-2d9361a6523d">
烦请各位大佬帮忙！！！！

**Comment by ZacharyZcR** [comment]
代理问题，请自查。
