### ISSUE TITLE
增加功能

### ISSUE THREAD

**Issue by cwkiller** [shadow1ng/fscan#3]
增加功能指定一个ip列表然后扫描一小批常见web端口，只去跑http、https然后去除400状态码且访问以后跟随跳转提取title、状态码、返回包大小生成csv格式文件

**Comment by shadow1ng** [comment]
收到反馈，考虑如何添加该模块

**Comment by shadow1ng** [comment]
该功能推荐使用 -p 加常见web端口便可实现大部分需要。
因为使用-p 指定非爆破服务的端口后，只会跑这些端口的http信息。关于跳转，golang的http包已默认302跟随跳转，不过不支持js跳转。默认以txt保存url 、状态码、标题的结果,以txt保存会比csv便捷。
