### ISSUE TITLE
redis模块扫描改配置问题

### ISSUE THREAD

**Issue by R17a-17** [shadow1ng/fscan#307]
目前redis扫描的时候如果存在未认证问题，默认就做了修改配置动作，有时候可能会造成业务影响。
能否添加扫描参数，通过reids参数指定扫描方式：

1. 扫描未授权不做配置修改
2. 扫描未授权+尝试修改配置
3. 扫描未授权+写文件

**Comment by shadow1ng** [comment]
加了-noredis参数可以跳过Testwrite
