### ISSUE TITLE
若干功能&优化建议

### ISSUE THREAD

**Issue by iconquestion** [shadow1ng/fscan#312]

**Comment by shadow1ng** [comment]
说得很好。第一个你咋实现

**Comment by ICONQUESTION** [comment]
> 说得很好。第一个你咋实现

nmap --resume了解一下？
而且，这种技术性问题不应该由我们用户解决吧

**Comment by lz520520** [comment]
这几个功能感觉很不错，你想法很好，要不你提个PR，我觉得既然是开源项目，就需要大家一起贡献，你有想法就可以去实现下

**Comment by shadow1ng** [comment]
> > 说得很好。第一个你咋实现
> 
> nmap --resume了解一下？ 而且，这种技术性问题不应该由我们用户解决吧

"而且" 、"技术性问题不应该用户解决"
"技术性问题"都不愿意思考，大概率是(或容易走向)非技术人员或脚本小子?
虽然实现的方法很多，比如把没扫到的ip、port保存下来。但"用户"不是"客户"。用户，免费开源的工具，并不意外着所有的事情都是丢给作者就行，而是对一些重要需求提一些基本思路、pr啥的，更不是爹。

**Comment by Liki4** [comment]
> 希望可以增加以下功能：
> 
> 1. 按Ctrl+C退出后保存当前进度，下次扫描时从上次保存的进度继续进行
> 2. 不同的输出文件格式，便于导入其他软件整理分析
> 3. 指定超时重传次数
> 4. 产生结果后立即追加写入到输出文件，避免程序被异常终止时零输出
> 5. 记忆用户自定义默认扫描端口，而不是每次使用-pa或-pn来增加或去除端口
> 6. 每次按Enter立即打印当前进度百分比
> 7. 将常见端口按照类型分类，如Web（80、443、8080等），database（1433、3306、5432等），并支持用户直接引用分类的名称作为扫描对象
>    谢谢！

这几个功能感觉很不错，你想法很好，要不你提个PR，我觉得既然是开源项目，就需要大家一起贡献，你有想法就可以去实现下

**Comment by wanswu** [comment]
> 希望可以增加以下功能：
> 
> 1. 按Ctrl+C退出后保存当前进度，下次扫描时从上次保存的进度继续进行
> 2. 不同的输出文件格式，便于导入其他软件整理分析
> 3. 指定超时重传次数
> 4. 产生结果后立即追加写入到输出文件，避免程序被异常终止时零输出
> 5. 记忆用户自定义默认扫描端口，而不是每次使用-pa或-pn来增加或去除端口
> 6. 每次按Enter立即打印当前进度百分比
> 7. 将常见端口按照类型分类，如Web（80、443、8080等），database（1433、3306、5432等），并支持用户直接引用分类的名称作为扫描对象
>    谢谢！

这几个功能感觉很不错，你想法很好，要不你提个PR，我觉得既然是开源项目，就需要大家一起贡献，你有想法就可以去实现下

**Comment by wgetnz** [comment]
> > 说得很好。第一个你咋实现
> 
> nmap --resume了解一下？ 而且，这种技术性问题不应该由我们用户解决吧

又不是你爸爸，开源给你用你当自己是上帝啊，白嫖还理直气壮
