### ISSUE TITLE
1.8.3运行报错～

### ISSUE THREAD

**Issue by zhxknb1** [shadow1ng/fscan#316]
![image](https://github.com/shadow1ng/fscan/assets/59738277/4451ae5c-a8f8-49f6-b313-37abcdfb1e5c)

**Comment by daymissed** [comment]
+1,还以为我编译的有问题.

**Comment by shadow1ng** [comment]
端口扫描这个我昨天修过了，还存在？

**Comment by zhxknb1** [comment]
<img width="1270" alt="image" src="https://github.com/shadow1ng/fscan/assets/59738277/ee49ba35-ad0d-4760-b8bf-2bbd04b280cf">
