### ISSUE TITLE
作者好，反馈个redis插件嗅探 /var/spool/cron 目录能写后，在恢复的问题 

### ISSUE THREAD

**Issue by pe4ch** [shadow1ng/fscan#320]
背景是我们发现研发会在 /var/spool/cron 目录里写 dump.db 找原因发现，本身这台服务器就是redis的未授权 空密码 0.0.0.0 ，我们在用fscan 做内部渗透后，fscan 会改 dir 目录， 看代码是这个testwrite 函数，逻辑应该是现获取当前redis的目录，在test 能否写入，都ok后再给恢复，不然这种测试是有脏数据破坏逻辑的，在非渗透场景，只是内部的测试场景就不完美了。 

func testwrite(conn net.Conn) (flag bool, flagCron bool, err error) {
	var text string
	_, err = conn.Write([]byte("CONFIG SET dir /root/.ssh/\r\n"))
	if err != nil {
		return flag, flagCron, err
	}
	text, err = readreply(conn)
	if err != nil {
		return flag, flagCron, err
	}
	if strings.Contains(text, "OK") {
		flag = true
	}
	_, err = conn.Write([]byte("CONFIG SET dir /var/spool/cron/\r\n"))
	if err != nil {
		return flag, flagCron, err
	}
	text, err = readreply(conn)
	if err != nil {
		return flag, flagCron, err
	}
	if strings.Contains(text, "OK") {
		flagCron = true
	}
	return flag, flagCron, err
}

**Comment by shadow1ng** [comment]
加了-noredis参数可以跳过Testwrite

**Comment by s1rius7** [comment]
好像加了参数也不行

**Comment by shadow1ng** [comment]
> 好像加了参数也不行

更新了
