### ISSUE TITLE
弱口令扫描结果显示有问题。

### ISSUE THREAD

**Issue by ghost** [shadow1ng/fscan#323]
![image](https://github.com/shadow1ng/fscan/assets/37506393/ae8bd49a-b973-4514-b558-04a1f5fa93bb)

![image](https://github.com/shadow1ng/fscan/assets/37506393/3221949d-9d15-4713-9d40-5acc3773cd8f)
![image](https://github.com/shadow1ng/fscan/assets/37506393/9468e1b0-ba30-4ac7-913e-3baaaad254c5)

**Comment by lacv587666** [comment]
> 是误报？还是正确的用户名应该是system？

正确的是 system

**Comment by lacv587666** [comment]
> 是误报？还是正确的用户名应该是system？

 sys 这个账号不存在的，我觉得应该是显示出问题了，已经检测出来存在弱口令，但是显示的账号名缺不对。

**Comment by shadow1ng** [comment]
oracle数据库默认的账号用户名为sys和system
他这里是提示连接时应该加上sysdba
https://blog.csdn.net/weixin_36272673/article/details/116530953
