### ISSUE TITLE
编译暴panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by CIDE-0409** [shadow1ng/fscan#325]
作者你好，不知道为什么，昨天重新编译运行之后，发现能正常扫描端口，端口扫描完之后就暴panic: runtime error: invalid memory address or nil pointer dereference这个的错误了，我重新下载源码编译也不行，不知道为什么。
完整的运行过程是这样的：
start infoscan
(icmp) Target 192.168.85.160  is alive
[*] Icmp alive hosts len is: 1
192.168.85.160:8161 open
192.168.85.160:8888 open
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xec1705]

goroutine 81 [running]:
github.com/shadow1ng/fscan/Plugins.PortConnect({{0xc000476010?, 0x0?}, 0x0?}, 0x0?, 0x0?, 0x0?)
        C:/Users/Administrator/Desktop/fscan-1.8.3(1)/fscan-1.8.3/Plugins/portscan.go:77 +0x105
github.com/shadow1ng/fscan/Plugins.PortScan.func2()
        C:/Users/Administrator/Desktop/fscan-1.8.3(1)/fscan-1.8.3/Plugins/portscan.go:55 +0x79
created by github.com/shadow1ng/fscan/Plugins.PortScan in goroutine 1
        C:/Users/Administrator/Desktop/fscan-1.8.3(1)/fscan-1.8.3/Plugins/portscan.go:53 +0x3a6
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xec1705]

goroutine 74 [running]:
github.com/shadow1ng/fscan/Plugins.PortConnect({{0xc000476010?, 0x0?}, 0x0?}, 0x0?, 0x0?, 0x0?)
        C:/Users/Administrator/Desktop/fscan-1.8.3(1)/fscan-1.8.3/Plugins/portscan.go:77 +0x105
github.com/shadow1ng/fscan/Plugins.PortScan.func2()
        C:/Users/Administrator/Desktop/fscan-1.8.3(1)/fscan-1.8.3/Plugins/portscan.go:55 +0x79
created by github.com/shadow1ng/fscan/Plugins.PortScan in goroutine 1
        C:/Users/Administrator/Desktop/fscan-1.8.3(1)/fscan-1.8.3/Plugins/portscan.go:53 +0x3a6

**Comment by CIDE-0409** [comment]
作者你好，我下了fscan-1.8.2的版本编译后，是可以正常运行的，fscan-1.8.3的还是不行。

**Comment by CIDE-0409** [comment]
作者没事了，我找到解决办法了，把1.8.2的portscan.go文件替换到1.8.3的文件就好了

**Comment by shadow1ng** [comment]
这个已经修过了，你下载最新的代码或最新tag里的就行
