### ISSUE TITLE
tomcat弱口令没爆破出来

### ISSUE THREAD

**Issue by liulangma0** [shadow1ng/fscan#33]
Authorization: Basic {{payload}}
![image](https://user-images.githubusercontent.com/76773206/110593747-ee7afa80-81b6-11eb-90ab-2a9a318276cd.png)

**Comment by shadow1ng** [comment]
好了已修复,某个变量填错了
![image](https://user-images.githubusercontent.com/39651966/110609131-deb7e200-81c7-11eb-82ee-930e45e45b0c.png)
