### ISSUE TITLE
9100端口问题

### ISSUE THREAD

**Issue by kkll5875** [shadow1ng/fscan#333]
1、默认端口：(default "21,22,80,81,135,139,443,445,1433,1521,3306,5432,6379,7001,8000,8080,8089,9000,9200,11211,27017")
实际应用中，fscan会扫描到 9100。

**Comment by shadow1ng** [comment]
默认还有top200 web

**Comment by kkll5875** [comment]
-pn 9100 能否禁用 web 访问 9100？
________________________________
发件人: 影舞者 ***@***.***>
发送时间: 2024年2月21日 15:57
收件人: shadow1ng/fscan ***@***.***>
抄送: ***@***.*** ***@***.***>; Author ***@***.***>
主题: Re: [shadow1ng/fscan] 9100端口问题 (Issue #333)


默认还有top200 web

―
