### ISSUE TITLE
默认的爆破的账号密码时写在哪个文件里呀

### ISSUE THREAD

**Issue by shannaburns** [shadow1ng/fscan#338]
还有账密表总量多大，然后用了pwdf pw.txt参数之后是会追加这些密码，还是覆盖掉原来的默认密码，只爆pw.txt

**Comment by shadow1ng** [comment]
1.config.go里有写
2.只爆pw.txt

**Comment by shannaburns** [comment]
有追加的参数不，还是现在就只有 只爆pw.txt的选项，我看项目里代码用的apend的函数加字典的，还以为时追加
