### ISSUE TITLE
你好烙铁，爆破模块能不能加入telnet协议爆破呢？

### ISSUE THREAD

**Issue by dracodong** [shadow1ng/fscan#346]

**Comment by dracodong** [comment]
<img width="187" alt="image" src="https://github.com/shadow1ng/fscan/assets/36252282/77bc0624-819b-469e-9a6f-cc4039059aaf">

**Comment by 845318843** [comment]
还有 vnc协议爆破

**Comment by ZacharyZcR** [comment]
> 还有 vnc协议爆破

已添加
