### ISSUE TITLE
运行异常

### ISSUE THREAD

**Issue by cseroad** [shadow1ng/fscan#350]
没有任何参数，运行异常

<img width="693" alt="image" src="https://github.com/shadow1ng/fscan/assets/59865739/4ba2b8f2-4e4d-48ac-b712-1fc477a79eb2">

**Comment by kaka77** [comment]
我也是遇到这样。。。

**Comment by kaka77** [comment]
系统是windows server 2008r2

**Comment by cseroad** [comment]
go版本问题导致的
