### ISSUE TITLE
指定A段时执行完ping扫描后停止

### ISSUE THREAD

**Issue by uyid** [shadow1ng/fscan#36]
参数:
 -h 10.1.1.1/8 -p 7001,7002,8880 -m webtitle 或
-h 10.1.1.1/8 -p 7001,7002,8880
ping扫描后自动停止,无报错
改为 -h 10.1.1.1/16 -p 7001,7002,8880 -m webtitle 正常运行

**Comment by shadow1ng** [comment]
目前-h 10.1.1.1/8，只扫*.*.*.1和*.*.*.254，主要用于扫描存活网关。当时感觉上千万个ip，扫描器量太大了，就用/8去探测网关，再用/16去扫存活B段

**Comment by uyid** [comment]
综合下吧,扫完网段再扫/16

**Comment by shadow1ng** [comment]
是指扫完/8网段，然后自动对存活的网段进行/16或/24扫描？

**Comment by uyid** [comment]
嗯嗯,是的,大佬.
