### ISSUE TITLE
something error!

### ISSUE THREAD

**Issue by 0xAcctracy** [shadow1ng/fscan#360]
something error when i am try to br host!

Use command is: fscan64.exe -hf 3389.txt -t 50 -np -p 3389 -u administrator -pwd 1qaz@WSX -nopoc -o 3389.txt

start vulscan

   ___                              _    
  / _ \     ___  ___ _ __ __ _  ___| | __ 
 / /_\/____/ __|/ __| '__/ _` |/ __| |/ /
/ /_\\_____\__ \ (__| | | (_| | (__|   <    
\____/     |___/\___|_|  \__,_|\___|_|\_\   
                     fscan version: 1.8.4
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xdc3f0d]

goroutine 1043 [running]:
github.com/tomatome/grdp/protocol/sec.(*Client).sendClientRandom(0xc00057a5a0)
	github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/protocol/sec/sec.go:630 +0x12d
github.com/tomatome/grdp/protocol/sec.(*Client).connect(0xc00057a5a0, {0xc0005a6c40, 0x3, 0x4}, {0xc0006b89a0, 0x2, 0x2}, 0x3ea, {0xc000495a70, 0x2, ...})
	github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/protocol/sec/sec.go:463 +0x3d4
reflect.Value.call({0x11c3100?, 0xc000483af0?, 0x12c0140?}, {0x12c15a4, 0x4}, {0xc0006f8f60, 0x4, 0x4?})
	reflect/value.go:596 +0xca6
reflect.Value.Call({0x11c3100?, 0xc000483af0?, 0xc00072ff48?}, {0xc0006f8f60?, 0x12c0140?, 0xc000407a00?})
	reflect/value.go:380 +0xb9
github.com/tomatome/grdp/emission.(*Emitter).callListeners.func1({0x11c3100?, 0xc000483af0?, 0x0?})
	github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/emission/emitter.go:226 +0x405
created by github.com/tomatome/grdp/emission.(*Emitter).callListeners in goroutine 1042
	github.com/tomatome/grdp@v0.0.0-20211231062539-be8adab7eaf3/emission/emitter.go:201 +0x8b

**Comment by SecureKaiser** [comment]
我也是

**Comment by SecureKaiser** [comment]
我也是

**Comment by ZacharyZcR** [comment]
Please update to latest version.
