### ISSUE TITLE
老哥，可以更新个指定单一账号密码爆破吗

### ISSUE THREAD

**Issue by ljlsec** [shadow1ng/fscan#361]
在爆破ssh时候可以-c进行whoami&ipconfig
但是爆破Windows时候有种场景，ip账号密码为
192.168.1.1 admin admin@001
192.168.1.197 admin admin@197
这种的怎么可以批量实现爆破一个c段呢，可以类似bp爆破的第三个模块那样吗。

**Comment by mlxwlX** [comment]
-user 指定用户名
-userf 指定用户名字典
-pwd 指定密码
-pwdf 指定密码字典

**Comment by shadow1ng** [comment]
这个-pwdf不是一直都有嘛



------------------ 原始邮件 ------------------
发件人: mlxwlX ***@***.***&gt;
发送时间: 2024年7月25日 13:32
收件人: shadow1ng/fscan ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [shadow1ng/fscan] 老哥，可以更新个指定单一账号密码爆破吗 (Issue #361)





 
-user 指定用户名
 -userf 指定用户名字典
 -pwd 指定密码
 -pwdf 指定密码字典
