### ISSUE TITLE
师傅，求救！我两台笔记本，在扫描大量目标时，电脑就会蓝屏，能帮忙分析下为什么嘛？一台笔记本 i9 32g、一台笔记本 i9 64g，但是fscan我工作中经常用到，真的好难受。

### ISSUE THREAD

**Issue by ss3931** [shadow1ng/fscan#366]
师傅，求救！我两台笔记本，在扫描大量目标时，电脑就会蓝屏，能帮忙分析下为什么嘛？一台笔记本 i9 32g、一台笔记本 i9 64g，但是fscan我工作中经常用到，真的好难受。

**Comment by shadow1ng** [comment]
没遇到过蓝屏问题，蓝屏没报错信息也不好分析，实在不行就分批扫描吧。win7上低配置扫描也没遇到过蓝屏问题，一般顶多就是异常退出，所以不好分析。





------------------ 原始邮件 ------------------
发件人: BackSpace ***@***.***&gt;
发送时间: 2024年7月24日 22:10
收件人: shadow1ng/fscan ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [shadow1ng/fscan] 师傅，求救！我两台笔记本，在扫描大量目标时，电脑就会蓝屏，能帮忙分析下为什么嘛？一台笔记本 i9 32g、一台笔记本 i9 64g，但是fscan我工作中经常用到，真的好难受。 (Issue #366)





 
师傅，求救！我两台笔记本，在扫描大量目标时，电脑就会蓝屏，能帮忙分析下为什么嘛？一台笔记本 i9 32g、一台笔记本 i9 64g，但是fscan我工作中经常用到，真的好难受。

**Comment by 845318843** [comment]
intel 13代会蓝屏，原因未知。 amd则一切正常

**Comment by AnkioTomas** [comment]
蓝屏代码呢？
做安全的不知道有蓝屏分析工具么........

**Comment by ZacharyZcR** [comment]
请提供更多信息

**Comment by ss3931** [comment]
> 蓝屏代码呢？ 做安全的不知道有蓝屏分析工具么........

当然分析过了，定位内存问题换了内存，还是一样蓝屏，我可不敢说我是做安全的.........，你才是。
