### ISSUE TITLE
rules.go中的code和body的区别是什么

### ISSUE THREAD

**Issue by chz2008** [shadow1ng/fscan#372]
请问rules.go中定义的是指纹识别的规则吗？  那么var RuleDatas = []RuleData{
	{"宝塔", "body", "(app.bt.cn/static/app.png|安全入口校验失败|<title>入口校验失败</title>|href=\"http://www.bt.cn/bbs)"},
	{"深信服防火墙类产品", "code", "(SANGFOR FW)"},   
 这个里面的body和code的区别是什么？

**Comment by shadow1ng** [comment]
用code就行
