### ISSUE TITLE
扫B段的时候出现主机存活与端口漏掉的情况

### ISSUE THREAD

**Issue by 3hm1ly** [shadow1ng/fscan#38]
扫B段的时候出现主机存活与端口漏掉的情况，并且每次扫描结果均不同，默认icmp模式
C段没有这种情况

**Comment by shadow1ng** [comment]
icmp连续大规模扫描时，存活率确实会有波动。考虑后续加上arp等存活检测方式，或者加-np参数跳过存活检测。

**Comment by Buffedon** [comment]
压缩包里面没有fscan.exe文件，执行不了那些命令怎么办
