### ISSUE TITLE
安装时报错。undefined: FcgiScan

### ISSUE THREAD

**Issue by Sadoshi** [shadow1ng/fscan#380]
![image](https://github.com/user-attachments/assets/7a891623-25e6-4924-b847-146da765837b)
到这一步报错。即使删了源码重新执行，也是这里卡住

**Comment by Sadoshi** [comment]
发现是下载的zip压缩包里面缺了这个文件

**Comment by shadow1ng** [comment]
![image](https://github.com/user-attachments/assets/f8023c6c-df16-4b74-97f1-528693c26739)

**Comment by ZacharyZcR** [comment]
已经准备更新到2.0.0版本，请在更新后重新检查该问题
