### ISSUE TITLE
编译大小问题

### ISSUE THREAD

**Issue by Erg0u** [shadow1ng/fscan#381]
你好，
        使用readme中的编译参数：go build -ldflags="-s -w " -trimpath main.go，  upx -9 fscan.exe，编译结果比release页发布文件大，
请问有其他的编译优化步骤吗？

**Comment by shadow1ng** [comment]
github action里有完整编译过程。而且大也大不了多少，最多就半m，无所谓吧

**Comment by Erg0u** [comment]
好的。我查了些go编译优化的资料，看这个编译比较小，以为有其他方式。
