### ISSUE TITLE
fscan报错问题

### ISSUE THREAD

**Issue by cclsh** [shadow1ng/fscan#391]
执行最新版fscan报错
Segmentation fault (core dumped) 
系统版本为
Linux matrix-test 5.15.0-1040-aws #45~20.04.1-Ubuntu SMP Tue Jul 11 19:08:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
fscan1.6版本可以

**Comment by ZacharyZcR** [comment]
请提供更多信息

**Comment by shadow1ng** [comment]
已换成go 1.20编译
