### ISSUE TITLE
火绒报毒

### ISSUE THREAD

**Issue by lifetin** [shadow1ng/fscan#393]
![image](https://github.com/user-attachments/assets/cb92853a-d0eb-430a-8dac-1c80b5534236)

**Comment by lifetin** [comment]
![image](https://github.com/user-attachments/assets/0cf3addc-3789-4e85-8efa-0569c2b3b7dc)

**Comment by shadow1ng** [comment]
各个杀软报毒不是很正常的事情吗，担心有毒就自行编译，免杀的放到github也只会被标记
