### ISSUE TITLE
安装总是报错，麻烦老师帮忙看一下

### ISSUE THREAD

**Issue by KevinKis** [shadow1ng/fscan#394]
![image](https://github.com/user-attachments/assets/0bf0cd7a-0dd6-494b-b6e8-f1bf67a98dfe)
┌──(root㉿kali)-[/home/kali/Desktop/fscan-main]
└─# go build -ldflags="-s -w " -trimpath main.go
go build: when using gccgo toolchain, please pass linker flags using -gccgoflags, not -ldflags
# github.com/icodeface/tls/internal/cpu
/data/go/pkg/mod/github.com/icodeface/tls@v0.0.0-20190904083142-17aec93c60e5/internal/cpu/cpu_x86.s:7:10: fatal error: textflag.h: No such file or directory
    7 | #include "textflag.h"
      |          ^~~~~~~~~~~~
compilation terminated.

按照网上的操作步骤，我也安装了go语言环境，并且对zshrc文件做了配置。但是在解析的时候就会出现这个报错。

**Comment by KevinKis** [comment]
在执行go build -ldflags="-s -w " -trimpath main.go报错的

**Comment by shadow1ng** [comment]
CGO_ENABLED=0 go build -ldflags="-s -w " -trimpath main.go 试试

**Comment by ZacharyZcR** [comment]
需要提供更多信息
