### ISSUE TITLE
只填一个ip的时候无法破解ssh

### ISSUE THREAD

**Issue by k79e** [shadow1ng/fscan#41]
他就扫描下然后就停了 这个正常么?

**Comment by k79e** [comment]
scan end
后面没有任何新内容 加了和不加都一样哇

他就是扫完port就正常结束了 没执行破解操作 设定下范围 改2个ip他就又能破解了...

**Comment by shadow1ng** [comment]
好吧。-debug的话，10秒内没输出才会提示报错。我改成自定义时间试试。然后再测试一下试试

**Comment by shadow1ng** [comment]
师傅重新下载一下,然后-debug 0试试？

**Comment by k79e** [comment]
没输出. 但是我改成2个ip之后 有时候也抽风

161.35.168.b:22 open
161.35.168.a:22 open
[-]  161.35.168.b:22 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
scan end
这时候2个ip也抽风了下 a的没见报错 直接就这么停了
后面试了几次然后2个ip的又正常了

1个的始终都是扫完端口就消失了

**Comment by shadow1ng** [comment]
a有点点奇怪。师傅可以试试在ssh.go里fmt.Println(err)试试

**Comment by shadow1ng** [comment]
我重新上传了releases，师傅再试试-debug 0试试

**Comment by k79e** [comment]
版本号还是1.5.1啊

**Comment by shadow1ng** [comment]
我重新上传了文件，但没重新发布新版本号

**Comment by k79e** [comment]
看起来正常了 有ssh流量了!

**Comment by k79e** [comment]
不对 我用的win的正常的
linux的还是老样子

**Comment by shadow1ng** [comment]
好像是有点问题，我看看

**Comment by shadow1ng** [comment]
已修复。由于协程过快，导致了跳过
