### ISSUE TITLE
是否能加一种新的连接中断方式?

### ISSUE THREAD

**Issue by k79e** [shadow1ng/fscan#42]
直接在中断的时候 给他发送rst包 (就是那个fin,ack 改成rst,ack)
那样连接就被打掉了 不会有什么短连接了 连接应该直接不见了

这个方式在syn扫描和中断短连接都可以用 不清楚实现难度大不大

**Comment by shadow1ng** [comment]
是为了解决time_wait占用问题？

**Comment by shadow1ng** [comment]
修改的话，目前只有思路修改端口扫描模块的。 像其他ssh、mysql爆破的，不容易修改

**Comment by k79e** [comment]
不过还好看起来并不是TW太多造成机器负载高的
