### ISSUE TITLE
已完成的日志记录的ip依然在扫描

### ISSUE THREAD

**Issue by k79e** [shadow1ng/fscan#43]
ssh 35.198.203.xxx:22 root 0048 ssh: handshake failed: ssh: unable to authenticate, **attempted methods [none]**, no supported methods remain

他这种none的 是不是不支持密码验证的? 如果是的话这bug严重哇
不支持验证为什么他还一直跑流量呢!??
//我于是手动打开ssh 结果发现他是公钥验证的 所以目前这个问题很大

又看了下 发现同一个ip 出现了2个日志
已完成 1680/1781 [-] ssh 34.97.91.a:22 root 1914 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
已完成 1709/1810 [-] ssh 34.97.91.a:22 root 2046 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

**Comment by shadow1ng** [comment]
好的，感谢反馈，已更新
https://github.com/shadow1ng/fscan/commit/067322203dee5f0c4da8890eb7fcd5ee4a831190
