### ISSUE TITLE
webtitle存在乱码

### ISSUE THREAD

**Issue by TryA9ain** [shadow1ng/fscan#46]
![image](https://user-images.githubusercontent.com/51145610/115345485-7229fd00-a1e1-11eb-92a3-031da16ac763.png)
![image](https://user-images.githubusercontent.com/51145610/115345606-9f76ab00-a1e1-11eb-8e55-b4c037403589.png)

**Comment by shadow1ng** [comment]
已加入gbk解码~

**Comment by TryA9ain** [comment]
> 已加入gbk解码〜
okkk，6666
