### ISSUE TITLE
weblogic漏洞扫描之后就会卡住

### ISSUE THREAD

**Issue by we1x4n** [shadow1ng/fscan#47]
扫描完weblogic的漏洞之后就会卡住，过一会进程自动结束，也没有scan end的返回

**Comment by shadow1ng** [comment]
尝试使用新版本，进行测试试试呢。  fscan -u http://xxxxx  或者  fscan -u http://xxxxx -proxy 8080 (抓包看看)

**Comment by shadow1ng** [comment]
没遇到过该问题，且无详细信息，无法复现与修改
