### ISSUE TITLE
爆破时会卡住

### ISSUE THREAD

**Issue by TryA9ain** [shadow1ng/fscan#48]
师傅，多次使用时发现：在跑B段、C段，机器多的时候 mysql、ftp、mssql这些爆破模块会卡住不动，不按ctrl+c的话也不知道要等多久才能结束，有什么办法解决这个问题吗？

**Comment by shadow1ng** [comment]
默认是120秒内没有响应的话，就会输出当前进度和报错情况，看来默认时间120秒还是有点久了，我调整默认成60秒试试。这个值也可以使用-debug参数控制。  fscan -h xxx/16 -debug 10  (10秒内没出新结果的话，就打印当前进度)

**Comment by TryA9ain** [comment]
> 默认是120秒内没有响应的话，就会输出当前进度和报错情况，看来默认时间120秒还是有点久了，我调整默认成60秒试试。这个值也可以使用-debug参数控制。 fscan -h xxx/16 -debug 10 (10秒内没出新结果的话，就打印当前进度)

是10秒内没爆破出口令就进行下一个漏洞的探测对吗？

**Comment by shadow1ng** [comment]
10秒内没有新的扫描进度，就会输出  
已完成  a/b 以及当前在爆破什么

**Comment by TryA9ain** [comment]
> 10秒内没有新的扫描进度，就会输出
> 已完成 a/b 以及当前在爆破什么

好的，我尝试一下

**Comment by TryA9ain** [comment]
> 10秒内没有新的扫描进度，就会输出
> 已完成 a/b 以及当前在爆破什么

师傅问一下 ：是不是最后才是执行爆破模块？

**Comment by shadow1ng** [comment]
对,icmp -> portscan -> 按端口顺序爆破或漏洞扫描

**Comment by 1testnew** [comment]
![卡住](https://github.com/user-attachments/assets/ca42bf1d-f243-450e-a49b-d10477d72be2)
师傅我现在扫内网时候会卡住，用的是1.8.4版本，语法如下f.exe -h xxxxxxx/24 -pwdf top50.txt -t 200 -debug 10 -o test.txt
有什么办法解决吗？就是卡在不动一天
