### ISSUE TITLE
我一个朋友的一些建议

### ISSUE THREAD

**Issue by lovelyjuice** [shadow1ng/fscan#49]
A:
你之前说最新的fscan有什么问题了？

XXXXXX:
还是有乱码

A:
还有其他吗

XXXXXX:
指result.txt里面的乱码

A:
![image](https://user-images.githubusercontent.com/20644461/116640587-83bb9380-a99d-11eb-8e6c-d99486588d5e.png)

A:
他只处理了这三种编码 ISO也很常见 没加进去

XXXXXX:
原来如此，给他提个issue

A:
自己改还快些

A:
![image](https://user-images.githubusercontent.com/20644461/116640604-8cac6500-a99d-11eb-967a-f17121c29410.png)

A:
除了443 其他都用http协议访问 难怪会漏报

XXXXXX:
继续提issue

XXXXXX:
让他两种都试试

A:
我先看完吧 他后面有个函数好像能识别https的 另外还有处理

A:
还真的是只识别443端口，另外就是302跳转他也只跳一次，昨天我爆破好几个站点都是跳三次的，虽然第一次登陆可能一般只会有一次跳转

XXXXXX:
给他提issuse

A:
你去啊

A:
我不做伸手党

**Comment by shadow1ng** [comment]
感谢反馈
1. 乱码的模块，后续还可以加入别的编码
2. https的问题考虑过。所以除443，默认是先用http访问，如果识别是https那么会用https重新去访问
```
if resp.StatusCode == 400 && info.Url[:5] != "https" {
				info.Url = strings.Replace(info.Url, "http://", "https://", 1)
				return err, "https", CheckData
			}
	if result == "https" {
		err, result, CheckData = geturl(info, 1, CheckData)
}
```
如果还遇到访问不了的情况，可以继续反馈
3. 关于跳转的问题，也做了处理。
```
if flag == 1 {
			client = lib.ClientNoRedirect
		} else {
			client = lib.Client
		}
```
只有第一次访问会用不跳转的client进行访问。遇到跳转后，后续的访问，会使用跳转的client进行访问，由go进行处理，自动跟随多次跳转，然后才获取最终url的信息。
4. 还有什么觉得不太完善、或者有疑问的地方，可以继续反馈

**Comment by lovelyjuice** [comment]
乱码这个问题比较特殊，像这种情况 aHR0cDovLzE3MS4xMDkuMTE4LjIzOjk4Lw==

**Comment by shadow1ng** [comment]
关于title。程序设定的就是遇到跳转时获取2次title。一次是跳转前的，一次是跳转后的。
乱码的问题我也会根据反馈继续处理。 看了下，确实存在
我后面继续处理看看
![image](https://user-images.githubusercontent.com/39651966/116646106-ddc25600-a9a9-11eb-9dce-b0a16823335e.png)

**Comment by lovelyjuice** [comment]
奇怪了，怎么你扫描的时候第二次标题能正常显示，我昨天编译的版本就只能显示一个None。。。

**Comment by shadow1ng** [comment]
已修复。   
res.Header.Set("Accept-Encoding", "gzip, deflate")的问题，返回包是gzip类型，没有明文，所以识别不到。 我走了burp代理，burp帮做了处理所以正常。

**Comment by shadow1ng** [comment]
![image](https://user-images.githubusercontent.com/39651966/118617780-8a4b6700-b7f5-11eb-9770-41ccc11c48dd.png)
