### ISSUE TITLE
2003 运行不了该程序

### ISSUE THREAD

**Issue by TryA9ain** [shadow1ng/fscan#50]
师傅，反馈，2003运行失败
![image](https://user-images.githubusercontent.com/51145610/117418754-5eef8f00-af4e-11eb-8742-c4740838aa02.png)
![image](https://user-images.githubusercontent.com/51145610/117418844-7595e600-af4e-11eb-9ce0-7cdc5b6a1bf5.png)

**Comment by shadow1ng** [comment]
golang 1.16对低版本windows兼容性不是很好，这个我也没办法解决。  win03 最高支持 golang 1.10

**Comment by TryA9ain** [comment]
> golang 1.16对低版本windows兼容性不是很好，这个我也没办法解决。 win03 最高支持 golang 1.10

over
