### ISSUE TITLE
师傅。webshell 和cs下运行报错

### ISSUE THREAD

**Issue by TryA9ain** [shadow1ng/fscan#51]
![image](https://user-images.githubusercontent.com/51145610/117949636-e79e6e80-b344-11eb-83fc-fa55613cf080.png)

![image](https://user-images.githubusercontent.com/51145610/117949716-fe44c580-b344-11eb-85f0-62ba7d33ee2c.png)

**Comment by shadow1ng** [comment]
icmp监听需要高权限。 权限不足时，可以尝试 -np 或-ping参数

**Comment by x931890193** [comment]
``二师兄`` 试试用管理员启动
