### ISSUE TITLE
扫描打印机的时候崩溃，

### ISSUE THREAD

**Issue by lovelyjuice** [shadow1ng/fscan#52]
win10 x64 ，刚刚编译的最新版

PS D:\Tools> .\fscan.exe -h 192.168.101.177

   ___                              _
  / _ \     ___  ___ _ __ __ _  ___| | __
 / /_\/____/ __|/ __| '__/ _` |/ __| |/ /
/ /_\\_____\__ \ (__| | | (_| | (__|   <
\____/     |___/\___|_|  \__,_|\___|_|\_\
                     fscan version: 1.6.0
start infoscan
(icmp) Target '192.168.101.177' is alive
icmp alive hosts len is: 1
192.168.101.177:8080 open
192.168.101.177:139 open
192.168.101.177:80 open
192.168.101.177:21 open
192.168.101.177:443 open
192.168.101.177:9100 open
alive ports len is: 6
start vulscan
[*] WebTitle:http://192.168.101.177:8080 404 404 Not Found
panic: runtime error: slice bounds out of range [47:45]

goroutine 1107 [running]:
github.com/shadow1ng/fscan/Plugins.NetBIOS1(0xc0003e2180, 0xc0003aa620, 0xf, 0xc0003aa6c0, 0x9, 0xc000160930, 0x65, 0x0, 0x0, 0x0, ...)
        github.com/shadow1ng/fscan/Plugins/NetBIOS.go:128 +0x157f
github.com/shadow1ng/fscan/Plugins.NetBIOS(0xc0003e2180, 0x0, 0x0)
        github.com/shadow1ng/fscan/Plugins/NetBIOS.go:51 +0x75
reflect.Value.call(0xf18020, 0x1267a78, 0x13, 0x10279f9, 0x4, 0xc00054e000, 0x1, 0x1, 0xc000aa9e90, 0x80e358, ...)
        reflect/value.go:476 +0x907
reflect.Value.Call(0xf18020, 0x1267a78, 0x13, 0xc00054e000, 0x1, 0x1, 0xc000412b98, 0xc000a98600, 0xc000a98688)
        reflect/value.go:337 +0xc5
github.com/shadow1ng/fscan/Plugins.ScanFunc(0xc0003b0600, 0xc000b8e208, 0x3, 0xc000aa9f98, 0x1, 0x1, 0x0, 0x0, 0x803b5d, 0x12686a0, ...)
        github.com/shadow1ng/fscan/Plugins/scanner.go:102 +0x245
github.com/shadow1ng/fscan/Plugins.AddScan.func1(0xc000b8e208, 0x3, 0xc0003e2180, 0xc0003aabe4, 0xc00007c8a0)
        github.com/shadow1ng/fscan/Plugins/scanner.go:81 +0xcd
created by github.com/shadow1ng/fscan/Plugins.AddScan
        github.com/shadow1ng/fscan/Plugins/scanner.go:77 +0xdd

**Comment by shadow1ng** [comment]
使用 -pn 139 参数，跳过netbios扫描即可 （后面我再修修改模块

**Comment by shadow1ng** [comment]
已更新代码，重新编译试试

**Comment by lovelyjuice** [comment]
最新的代码已经没有问题了
