### ISSUE TITLE
ssh爆破字典

### ISSUE THREAD

**Issue by sysyz** [shadow1ng/fscan#54]
ssh字典缺少 root/root

**Comment by shadow1ng** [comment]
![image](https://user-images.githubusercontent.com/39651966/118224932-aaf28480-b4b6-11eb-90aa-9cf430fb473a.png)
config.go里面配置有这个字典了。是漏报了嘛？

**Comment by sysyz** [comment]
嗯，AIX服务器

**Comment by shadow1ng** [comment]
是指SSH遇到AIX服务器，会ssh扫描漏报？

**Comment by sysyz** [comment]
嗯嗯，AIX服务账户密码root/root扫不出来，漏报了。

**Comment by shadow1ng** [comment]
暂无环境测试，目前ssh库用的是官方包，这个得官方更新才行了

**Comment by shadow1ng** [comment]
已修复

**Comment by shadow1ng** [comment]
由于到时为了防止只允许私钥登录下还继续爆破，所以遇到"no supported methods remain"报错时，会就跳出该ssh爆破，但在官方ssh包下，密码错误时，也会报错 "no supported methods remain"。 目前暂时把该代码注释了
