### ISSUE TITLE
为何无法扫描内网

### ISSUE THREAD

**Issue by Oldman19** [shadow1ng/fscan#56]
情景：web服务器上通过nps设置socks5代理出来，攻击者本地连接socks5，并使用fscan扫描内网，发现没有任何成功。

**Comment by shadow1ng** [comment]
走s5代理需要加上-np 参数跳过icmp探测（icmp走不了s5代理）。并且最好设置-t xxx 设置较小线程

**Comment by Oldman19** [comment]
> 走s5代理需要加上-np 参数跳过icmp探测（icmp走不了s5代理）。并且最好设置-t xxx 设置较小线程

好的，谢谢大佬

**Comment by whami-root** [comment]
请问扫描支持设置代理吗，我尝试proxychains运行fscan，但不可以

**Comment by shadow1ng** [comment]
> 请问扫描支持设置代理吗，我尝试proxychains运行fscan，但不可以
tcp流量都能走socks5, 我用proxifer测试很稳定，用 -np跳过icmp检测即可

**Comment by whami-root** [comment]
软件是否可以自身支持代理，linux平台的proxychains我测试不能代理fscan。谢谢

**Comment by shadow1ng** [comment]
> 软件是否可以自身支持代理，linux平台的proxychains我测试不能代理fscan。谢谢

软件自身暂不支持
