### ISSUE TITLE
编译不成功

### ISSUE THREAD

**Issue by getin63** [shadow1ng/fscan#60]
大佬，请问为何编译不成功，

报错：
C:\Users\Getin\Desktop\fscan-main>go build -ldflags="-s -w " -trimpath main.go
# github.com/shadow1ng/fscan/Plugins
Plugins\ftp.go:4:2: imported and not used: "errors"
Plugins\ftp.go:8:2: imported and not used: "net"
Plugins\ms17017.go:130:4: undefined: MS17010EXP

**Comment by shadow1ng** [comment]
已g更新，再试试呢。

**Comment by getin63** [comment]
感谢大佬，现在可以了
