### ISSUE TITLE
-c命令执行不了。

### ISSUE THREAD

**Issue by poo-007** [shadow1ng/fscan#61]
用户名和密码写入文件中，运行命令执行不了，麻烦大佬给看下。
![1](https://user-images.githubusercontent.com/59350023/120418104-80e40200-c392-11eb-8b5a-85376467b7b1.jpg)

**Comment by shadow1ng** [comment]
这看起来没碰撞出密码，可以用 fscan -h xxx -pwd xxx -user xxx -c whoami -debug 0 看下？  -debug 0可以输出报错

**Comment by poo-007** [comment]
确实账户登录没成功。可是我现在改的密码就是这个，root/admin
![2](https://user-images.githubusercontent.com/59350023/120416152-40cf5000-c38f-11eb-843c-f8e4596825ab.jpg)

**Comment by shadow1ng** [comment]
![image](https://user-images.githubusercontent.com/39651966/120416616-05815100-c390-11eb-9898-1f4d4cb9de92.png)
我在kali下，ssh登录是可以的

**Comment by poo-007** [comment]
我有试了一下，直接输入账号密码是没问题的，但是指定文件就不不行，是不是密码文件格式有要求呀？
![4](https://user-images.githubusercontent.com/59350023/120416800-51cc9100-c390-11eb-915e-b828bad3ed25.jpg)
![5](https://user-images.githubusercontent.com/59350023/120416816-56914500-c390-11eb-9b94-12ee5b3563cf.jpg)

**Comment by shadow1ng** [comment]
![image](https://user-images.githubusercontent.com/39651966/120416877-76c10400-c390-11eb-855d-a8f3c618fbc3.png)
看起来是root用户名乱码了

**Comment by shadow1ng** [comment]
![image](https://user-images.githubusercontent.com/39651966/120417079-cdc6d900-c390-11eb-8702-f827f60a64da.png)
这是我在kali下的测试结果

**Comment by poo-007** [comment]
改成utf-8无bom格式编码成功了，谢谢大佬。大佬，手册资料太少，有没有内容全一些的？
![6](https://user-images.githubusercontent.com/59350023/120417663-c9e78680-c391-11eb-8cf7-c4c801f9536a.jpg)

**Comment by shadow1ng** [comment]
暂时没有手册，因为设计是为了简单易用，所以一般需要用的参数不多。-h -p -m -np -pwd -pwdf 这几个参数基本就够用了。有什么不懂的地方也可以提问

**Comment by poo-007** [comment]
好的，感谢大佬。
