### ISSUE TITLE
json output support

### ISSUE THREAD

**Issue by freeAhao** [shadow1ng/fscan#64]
json格式输出，方便和其他工具配合。

**Comment by shadow1ng** [comment]
你是想要哪种json格式？
{
"ip:port":"output"
}这种？

**Comment by freeAhao** [comment]
> 你是想要哪种json格式？
> {
> "ip:port":"output"
> }这种？

加上-json参数后输出：

{"ip":"xxx","port":xx,"vuln":"xxx"}
{"ip":"xxx","port":xx,"vuln":"xxx"}
{"ip":"xxx","port":xx,"vuln":"xxx"}

格式不重要啦
