### ISSUE TITLE
师傅好，能考虑添加类似刺探内网边界的功能吗

### ISSUE THREAD

**Issue by 0neAtSec** [shadow1ng/fscan#69]
内置一些内网IP段网关地址。
比如入口点192.168.2.10，执行fscan -find 输出：
172.17.x.x/16
10.0.4.x/24
10.1.x.x/16
192.168.x.x/16

**Comment by shadow1ng** [comment]
师傅对这个有什么思路嘛

**Comment by 0neAtSec** [comment]
内置一些内网网关地址字典：
......
......
192.168.2.1
192.168.2.254
192.168.3.1
192.168.3.254
......
......

比如入口点192.168.5.10:
ping(192.168.2.1or254) 能通一个则输出192.168.2.x/24，满足2个或多个C段则升级输出为192.168.x.x/16

**Comment by 0neAtSec** [comment]
批处理的实现：
for /l %%i in (0,1,255) do (
  for /l %%k in (0,1,255) do (
    ping -w 1 -n 1 10.%%i.%%k.1 | findstr "TTL=" >nul || ping -w 1 -n 1 10.%%i.%%k.254 | findstr "TTL=" >nul
    if !errorlevel! equ 0 (echo 10.%%i.%%k.0/24 is alive ! >> alive.txt )
  )
)

for /l %%s in (16,1,31) do (
  for /l %%d in (0,1,255) do (
    ping -n 1 -w 1 172.%%s.%%d.1  | findstr "TTL=" >nul || ping -w 1 -n 1 172.%%s.%%d.254 | findstr "TTL=" >nul
    if !errorlevel! equ 0 (echo 172.%%s.%%d.0/24 is alive ! >> alive.txt )
  )
)

for /l %%t in (0,1,255) do (
  ping -n 1 -w 1 192.168.%%t.1  | findstr "TTL=" >nul || ping -n 1 -w 1 192.168.%%t.254 | findstr "TTL=" >nul
  if !errorlevel! equ 0 (echo 192.168.%%t.0/24 is alive ! >> alive.txt )
)

**Comment by shadow1ng** [comment]
A段的 -h xxx/8 即可( /8时只扫1和254)，如
fscan -h 10.0.0.0/8  
fscan -h 172.0.0.0/8   
B段的直接扫就行  
fscan -h 192.168.0.0/16

**Comment by 0neAtSec** [comment]
好的师傅 我还以为/8会ping所以的ip。感谢回答
