### ISSUE TITLE
B段扫描时只会探测存活,不会扫描

### ISSUE THREAD

**Issue by uyid** [shadow1ng/fscan#7]
./fscan_amd64_upx -h 10.1.1.1/16
这样的参数运行只会运行ping扫描,没执行扫描插件

**Comment by shadow1ng** [comment]
收到反馈，今天刚找到测试环境

**Comment by shadow1ng** [comment]
抱歉，我也没找到具体原因，因为我这边测试正常。可以尝试下载最新版，或者加大超时时间。
我这边应对措施是，后续看看添加一些 log功能，方便打印扫描进度，或者失败原因。
![image](https://user-images.githubusercontent.com/39651966/99757185-d14bee80-2b29-11eb-964a-663e8a290c63.png)

**Comment by shadow1ng** [comment]
已修复。正好遇到同样的情况，然后debug测试发现是socket占用过多。原因是icmp模块没有close,导致并发过大。
![image](https://user-images.githubusercontent.com/39651966/101050320-4524d700-35bf-11eb-9bd7-a028af18a6c7.png)
