### ISSUE TITLE
1.6.3报错

### ISSUE THREAD

**Issue by we1x4n** [shadow1ng/fscan#71]
操作系统：ubuntu
fscan版本：1.6.3
扫描时候报错，报错信息包含大量windows盘符路径信息
![image](https://user-images.githubusercontent.com/36219405/122848356-f280f180-d33b-11eb-8f46-dfd05d31eb18.png)

**Comment by shadow1ng** [comment]
我回头测试看看，可以先用1.6.2

**Comment by shadow1ng** [comment]
Ubuntu 18.04.4 LTS +   amd64 下没复现成功
师傅用的会不会是386的linux系统？
![image](https://user-images.githubusercontent.com/39651966/123222674-bd72cb80-d502-11eb-9f19-b65730c22aa7.png)

![image](https://user-images.githubusercontent.com/39651966/123222727-cc597e00-d502-11eb-82c6-e86624d7217a.png)

**Comment by we1x4n** [comment]
不是啊，是ubuntu amd64
![image](https://user-images.githubusercontent.com/36219405/123223354-6a4d4880-d503-11eb-8679-d44472cafc39.png)

**Comment by shadow1ng** [comment]
emmm 我这边没复现成功

**Comment by shadow1ng** [comment]
师傅方便提供测试目标+完整log嘛?
