### ISSUE TITLE
提交几个指纹

### ISSUE THREAD

**Issue by zxc12609** [shadow1ng/fscan#72]
提交几个指纹	

 {"Hadoop Applications", "code", "(/cluster/app/application)"},
	{"用友NC", "code", "(YONYOU NC | /Client/Uclient/UClient.dmg)"},
	{"用友IUFO", "code", "(iufo/web/css/menu.css)"},
	{"海昌OA", "code", "(/loginmain4/js/jquery.min.js)"},
	{"Jquery-1.7.2", "code", "(/webui/js/jquerylib/jquery-1.7.2.min.js)"},
	{"泛微E-Mobile", "code", "(E-Mobile)"},
	{"泛微E-Mobile", "headers", "(EMobileServer)"},

**Comment by shadow1ng** [comment]
感谢反馈，这就添加。
然后Jquery-1.7.2除了XSS还有什么用嘛？

**Comment by shadow1ng** [comment]
已添加
