### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by 430Q** [shadow1ng/fscan#81]
![image](https://user-images.githubusercontent.com/75164294/126424544-b6cf161c-2239-41b8-8424-454f6c28673f.png)
![image](https://user-images.githubusercontent.com/75164294/126424564-a605161a-5932-4cc3-b3b8-68c6ce912e5e.png)
![image](https://user-images.githubusercontent.com/75164294/126424612-ba41baff-aa79-4980-bf53-91d28ec68c87.png)

**Comment by shadow1ng** [comment]
go mod tidy试试

**Comment by 430Q** [comment]
get(*^_^*) thanks
&nbsp; &nbsp; &nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shadow1ng/fscan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 中午11:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shadow1ng/fscan] go build error (#81)





 
go mod tidy试试
