### ISSUE TITLE
这么慢吗，ssh一个IP 30行字典都跑不动

### ISSUE THREAD

**Issue by komomon** [shadow1ng/fscan#83]
![image](https://user-images.githubusercontent.com/52700174/127030464-181c3534-3ead-4f6e-84f0-2af4d30cd7fc.png)
其他工具秒出结果，这个扫了5分钟还没出结果。

**Comment by shadow1ng** [comment]
其他工具指的是？

**Comment by ZacharyZcR** [comment]
已优化。
