### ISSUE TITLE
smb爆破模块

### ISSUE THREAD

**Issue by whosisgood88** [shadow1ng/fscan#85]
师傅好，fscan弱口令扫的又快又全，在内网渗透中hash爆破也是比较常用的手段。
1、是否考虑向ladon那样增加smbhash爆破、wmihash爆破
2、另外当前smb爆破不支持域账号的smb爆破，是否考虑增加域账号爆破机制。
3、1+2 域账号的hash爆破

**Comment by shadow1ng** [comment]
golang 暂时没看到比较好用的smb包，github.com/stacktitan/smb/smb误报率太高了，我就默认没开启了。-m smb -domain xxx的话，是支持域用户的

**Comment by shadow1ng** [comment]
我本地有测试 https://github.com/C-Sto/goWMIExec  ，但还是有一些些问题，作者也没修复，所以我就没放上来了

**Comment by whosisgood88** [comment]
师傅好，关于smb的域账号爆破有漏报和误报的问题
测试环境中192.168.3.21是dc
192.168.3.30是域内普通机器。
对不同机器爆破smb对比超级弱口令存在不同结果
![smb1](https://user-images.githubusercontent.com/88481382/129148269-ed8ecf85-ef1a-410c-aa68-7e9f8395d178.png)

![smb2](https://user-images.githubusercontent.com/88481382/129148297-e5bca9b2-49d8-4a8f-8477-28206468419e.png)

**Comment by shadow1ng** [comment]
嗯，因为调用的第三方包github.com/stacktitan/smb 误报比较多，后面只能看看有没有别的合适包来替换了
