### ISSUE TITLE
Mac 终端挂proxychains扫描会显示所有端口都开放

### ISSUE THREAD

**Issue by AMJIYU** [shadow1ng/fscan#88]
<img width="815" alt="image" src="https://user-images.githubusercontent.com/21239564/129479313-2c3a171f-aadc-42be-b3f9-ee3518da5782.png">

**Comment by shadow1ng** [comment]
是fscan的问题还是proxychans对golang支持的问题？
用别的golang端口扫描工具也这样嘛？比如Servicescan

**Comment by shadow1ng** [comment]
可以使用graftcp进行代理

**Comment by Donek1** [comment]
佬，知道啥问题了吗

**Comment by ZacharyZcR** [comment]
> 佬，知道啥问题了吗

老版本貌似代理有问题，暂时可以用这个试试 https://github.com/killmonday/fscanx
