### ISSUE TITLE
有的内网扫描不知道为啥各种报错

### ISSUE THREAD

**Issue by cwkiller** [shadow1ng/fscan#9]
命令
fscan_upx.exe -h 10.30.1.1/16
![image](https://user-images.githubusercontent.com/19302055/100978689-b8a5f480-357d-11eb-995c-a29c04a3cbc8.png)

**Comment by shadow1ng** [comment]
应该是软件版本不兼容该系统版本，需要编译32位的fscan去进行扫描。(releases里的版本是64位的，不一定能兼容32位的系统)

**Comment by cwkiller** [comment]
> 应该是软件版本不兼容该系统版本，需要编译32位的fscan去进行扫描。（releases里的版本是64位的，不一定能兼容32位的系统或者低版本系统）

扫描存活的时候不报错

**Comment by shadow1ng** [comment]
我上次了fscan32位，可以尝试使用，看看是否正常~

**Comment by cwkiller** [comment]
> 我上次了fscan32位，可以尝试使用，看看是否正常~

不行这个存活都跑不了
![image](https://user-images.githubusercontent.com/19302055/100981196-6bc41d00-3581-11eb-9c7a-ad097ab74254.png)

**Comment by shadow1ng** [comment]
这有点玄学，能帮忙测试下非upx的32、64版本也是这样嘛？

**Comment by cwkiller** [comment]
> 这有点玄学，能帮忙测试下非upx的32、64版本也是这样嘛？

试了不行还是一样的报错，64位的能扫存活后面就开始报错，32位的直接报错

**Comment by shadow1ng** [comment]
收到，我回头找找低版本设备进行测试

**Comment by cwkiller** [comment]
> 收到，我回头找找低版本设备进行测试

![image](https://user-images.githubusercontent.com/19302055/100983991-0eca6600-3585-11eb-9325-2d386385fabc.png)

**Comment by shadow1ng** [comment]
应该是低版本系统兼容性问题，尝试使用fscan_win03.exe试试
