### ISSUE TITLE
go build -ldflags="-s -w " -trimpath 这个命令编译失败啊

### ISSUE THREAD

**Issue by Zxc123456zxc** [shadow1ng/fscan#95]
go: github.com/denisenkom/go-mssqldb@v0.10.0: Get "https://proxy.golang.org/github.com/denisenkom/go-mssqldb/@v/v0.10.0.mod": dial tcp 142.251.42.241:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
go: downloading github.com/jlaffaye/ftp v0.0.0-20210307004419-5d4190119067
go: downloading github.com/go-sql-driver/mysql v1.6.0
go: downloading github.com/denisenkom/go-mssqldb v0.10.0
go: downloading github.com/lib/pq v1.10.1
go: downloading github.com/saintfish/chardet v0.0.0-20120816061221-3af4cd4741ca
go: downloading github.com/stacktitan/smb v0.0.0-20190531122847-da9a425dceb8
go: downloading golang.org/x/crypto v0.0.0-20200728195943-123391ffb6de
go: downloading golang.org/x/net v0.0.0-20200301022130-244492dfa37a
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/golang/protobuf v1.3.4
go: downloading github.com/google/cel-go v0.6.0
go: downloading google.golang.org/genproto v0.0.0-20200416231807-8751e049a2a0
go: downloading gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
go: github.com/denisenkom/go-mssqldb@v0.10.0: Get "https://proxy.golang.org/github.com/denisenkom/go-mssqldb/@v/v0.10.0.mod": dial tcp 142.251.42.241:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by shadow1ng** [comment]
go env -w GOPROXY=https://goproxy.cn,direct  
go mod tidy  
go build -ldflags="-s -w " -trimpath

**Comment by Zxc123456zxc** [comment]
h

> 
> 
> go env -w GOPROXY=https://goproxy.cn,direct
> go mod tidy
> go build -ldflags="-s -w " -trimpath

谢谢，编译成功了
