### ISSUE TITLE
无法正常识别https站点

### ISSUE THREAD

**Issue by evasilence** [shadow1ng/fscan#96]

**Comment by shadow1ng** [comment]
fscan -u https://xxxx -debug 0 看下报错?

**Comment by shadow1ng** [comment]
试试1.6.3版本呢

**Comment by evasilence** [comment]
无法将该端口识别成正常的站点（截图用的是1.6.2，但1.6.3也无法将该端口正常识别）

**Comment by evasilence** [comment]
![image](https://user-images.githubusercontent.com/39252712/132461607-ef3ed3b3-2fe3-4e80-9ac9-8256625d5782.png)

**Comment by evasilence** [comment]
![image](https://user-images.githubusercontent.com/39252712/132461661-62c7d55f-dc03-4bd7-8429-52f27b522d09.png)

**Comment by shadow1ng** [comment]
然后看下 fscan -h xxx -p 44300 -debug 0   ？

**Comment by evasilence** [comment]
>fscan64.exe -h x.x.x.x -p 44300 -debug 0 -np

   ___                              _
  / _ \     ___  ___ _ __ __ _  ___| | __
 / /_\/____/ __|/ __| '__/ _` |/ __| |/ /
/ /_\\_____\__ \ (__| | | (_| | (__|   <
\____/     |___/\___|_|  \__,_|\___|_|\_\
                     fscan version: 1.6.3
start infoscan
alive ports len is: 1
start vulscan
x.x.x.x:44300 open
已完成 0/1 [-] webtitle http://x.x.x.x:44300 Get "http://x.x.x.x:44300": read tcp x.x.x.x:1080->x.x.x.x:44300: wsarecv: An existing connection was forcibly closed by the remote host.
已完成 1/1
scan end

**Comment by evasilence** [comment]
![image](https://user-images.githubusercontent.com/39252712/132462328-8da28947-e877-4d14-a4a3-6a0b62ca078c.png)

**Comment by shadow1ng** [comment]
行，那得改改了，http失败就走https

**Comment by evasilence** [comment]
感谢大佬

**Comment by shadow1ng** [comment]
更新代码了，师傅试试go build -ldflags="-s -w" -trimpath ，再运行试试？

**Comment by evasilence** [comment]
ok了，已经可以正常识别了
