### ISSUE TITLE
[Chore] license

### ISSUE THREAD

**Issue by noraj** [shadow1ng/fscan#97]
Hi,

Could you choose a license so we can include your tool in [BlackArch Linux](https://github.com/BlackArch/blackarch/pull/3235/).

here are the consequences of no license and why we can't share it: https://choosealicense.com/no-permission/

Thanks

**Comment by shadow1ng** [comment]
What should I do?

**Comment by shadow1ng** [comment]
like https://github.com/shelld3v/aquatone/blob/master/LICENSE.txt ?

**Comment by noraj** [comment]
Yeah MIT one for example.

**Comment by shadow1ng** [comment]
https://github.com/shadow1ng/fscan/blob/main/LICENSE.txt
