### ISSUE TITLE
ftp爆破会卡住

### ISSUE THREAD

**Issue by erma0** [shadow1ng/fscan#99]
内网扫C段发现到ftp爆破就卡住了，换了个公网测试结果也是一样
输出如下，等半天了还是卡在这两个ip

> 已完成 421/423 [-] ftp://47.100.105.245:21 ftp ftp1 530 Login or password incorrect!
已完成 421/423 [-] ftp://47.100.105.180:21 ftp ftp@111 530 Login or password incorrect!
已完成 421/423 [-] ftp://47.100.105.245:21 ftp Passw0rd 530 Login or password incorrect!
已完成 421/423 [-] ftp://47.100.105.180:21 ftp 123456789 530 Login or password incorrect!
已完成 421/423 [-] ftp://47.100.105.245:21 ftp 123456!a 530 Login or password incorrect!
已完成 421/423 [-] ftp://47.100.105.180:21 ftp abc123 530 Login or password incorrect!
已完成 421/423 [-] ftp://47.100.105.245:21 ftp Aa1234 530 Login or password incorrect!
已完成 421/423 [-] ftp://47.100.105.180:21 ftp Aa123456 530 Login or password incorrect!
已完成 421/423 [-] ftp://47.100.105.245:21 ftp 2wsx@WSX 530 Login or password incorrect!
已完成 421/423 [-] ftp://47.100.105.180:21 admin admin 530 Login or password incorrect!
已完成 421/423 [-] ftp://47.100.105.245:21 admin pass@123 530 Login or password incorrect!
已完成 421/423 [-] ftp://47.100.105.245:21 admin 123 530 Login or password incorrect!
已完成 421/423 [-] ftp://47.100.105.180:21 admin admin1 530 Login or password incorrect!
已完成 421/423 [-] ftp://47.100.105.245:21 admin admin#123 530 Login or password incorrect!

**Comment by shadow1ng** [comment]
已完成 421/423 ，说明99%的工作扫完了。只是有个别爆破线程卡住了，这种crtl c放弃就行。

**Comment by erma0** [comment]
这样直接退出就没有结果输出了吧
还有，FTP爆破是最后一步吗，强制退出会不会漏掉其他扫描

**Comment by shadow1ng** [comment]
这样退出也会有结果输出。
因为是边扫描边保存结果的。
强制退出不会漏掉其他扫描，因为你的扫描已经完成99%了，而且边扫描，边保存结果了
